### ISSUE TITLE
Change ALL CAPS messages to Sentence case

### ISSUE THREAD

**Issue by icemc** [opendatakit/briefcase#114]
Make pull and push messages such as "SUCCESS, FAILED" etc to be less Caps

**Comment by icemc** [comment]
@yanokwa I'm currently writing exams but will probably send in a PR tomorrow.

**Comment by yanokwa** [comment]
One easy way to find these messages is to do a search for some of these terms.
* SUC
* ERR
* FAI

**Comment by thomashhuang** [comment]
@yanokwa I can finish this up.

**Comment by yanokwa** [comment]
That'd be great. Just claim the issue using `@opendatakit-bot claim` and you'll be assigned to it.

**Comment by thomashhuang** [comment]
@opendatakit-bot claim

**Comment by dcbriccetti** [comment]
I suggest removing the "!"s from the messages.

**Comment by yanokwa** [comment]
Agreed with @dcbriccetti. 

But when doing the replacements, be careful because sometimes the '!' is used as a way to terminate sentences.
