### ISSUE TITLE
Spinner in proxy port settings don't increment or persist well

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#128]
* If I put in 999 as the port number and try to increment with the +, it doesn't increment. Anything below 999 works though. 
* Port numbers don't seem to persist in the UI between launches. It persists as far as connections though.

**Comment by yanokwa** [comment]
@daveycrockett Can you take care of these minor bugs? 

Please be sure to use a branch (and not your master) as specified in the [contribution guide](https://github.com/opendatakit/briefcase/blob/master/CONTRIBUTING.md).

**Comment by daveycrockett** [comment]
:+1: I'm on it!
