### ISSUE TITLE
Minor UI tweak on storage location padding

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#130]
I think the line on storage location needs a bit of padding at the top so it matches the other tabs. Looks like maybe 18 px?

**Good**
![screen shot 2017-06-12 at 10 16 22](https://user-images.githubusercontent.com/32369/27046271-ad848986-4f58-11e7-8abe-f0bcb357db7d.png)

**Not so good**
![screen shot 2017-06-12 at 10 16 30](https://user-images.githubusercontent.com/32369/27046270-ad7bf0f0-4f58-11e7-9088-df50fb06f4f5.png)

**Comment by yanokwa** [comment]
@daveycrockett This one is right up your alley!

**Comment by daveycrockett** [comment]
:+1: I'm on it!
