### ISSUE TITLE
Replace tabs with spaces

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#131]
The following classes have tabs that should be replaced with spaces. 
```
AggregateUtils.java
BadFormDefinition.java
BriefcaseFolderChooser.java
BriefcaseStorageLocationDialog.java
DatabaseUtils.java
ExportFolderChooser.java
ExportType.java
FormDefinitionFileChooser.java
FormTransferTable.java
HtmlConsts.java
HtmlStrUtil.java
LegacyServerConnectionDialog.java
MainBriefcaseWindow.java
ODKCollectFileChooser.java
PrivateKeyFileChooser.java
PushTransferPanel.java
ServerConnectionDialog.java
ServerFetcher.java
StringUtils.java
TransferFromODK.java
TransferInProgressDialog.java
WebUtils.java
XFormParameters.java
```

Use IntelliJ's conversion tool to convert the tabs with spaces, then uncomment out the following in checkstyle.xml.
```
    <module name="FileTabCharacter">
        <property name="eachLine" value="true"/>
    </module>
```

Run `./gradlew checkstyle` and fix any remaining issues.

To make code review easy, please make sure the PR has mostly whitespace changes.

**Comment by thomashhuang** [comment]
Is this still available to be worked on?

**Comment by lognaturel** [comment]
Hello @thomashhuang and welcome! As @dcbriccetti mentioned, there are a couple of big pull requests pending and it might be better to merge those first. 

That said, I suspect that `git rebase` plays nicely with whitespace changes. This could be verified by seeing if #179 rebases cleanly on top of #183. @thomashhuang is this something you could look into?

**Comment by thomashhuang** [comment]
@lognaturel I'll look into it
