### ISSUE TITLE
Add Google Analytics to Briefcase

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#137]
Better analytics will help with important design decisions.

In the settings, there should be a checkbox to disable analytics if desired. It should be checked by default.

**Comment by jpknox** [comment]
Hello yanokwa, I'd like to have a go at this.
I've found a few user-made libraries that interact with Google's Analytics API.
May I have this task assigned to me?

**Comment by yanokwa** [comment]
Welcome to ODK, @jpknox! Please have a go at this! 

What I'd like to get out of the analytics is what operating systems are in use, what version of ODK Briefcase is being run, and what users take (so maybe we track if they use the Pull/Push/Export) and what screens they switch to (Pull/Push/Export/Settings) in the GUI.

Bonus points if you can figure out command line usage as well.

**Comment by lognaturel** [comment]
Hi @jpknox! How is this looking? If you want to explore different options, we're happy to give feedback and ideas here. Also consider joining the developer Slack [here](http://slack.opendatakit.org/)!

**Comment by jpknox** [comment]
Hi Helene,


I've got the app to send my Google analytics account a message when it starts up, which includes the operating system in use.


I've been thinking about getting it to send a breakdown of the ratio of tab usage when the app shuts down, so we'll be able to track which tabs see the most usage - in terms of seconds active. This will require knowledge of Swing, of which I know very little; I've been working through a tutorial on Swing to help myself figure out the GUI.


Thank you for inviting me to the Slack channel, I'll hop in to it when I'm stuck or thinking about possibilities for the analytics.


Regards,

Joao Paulo Knox

________________________________

**Comment by yanokwa** [comment]
Keep up the great work, @jpknox! It'd be awesome to get this into the next monthly release (code freeze on Aug 23rd). If you run into Swing issues, please ask on the Slack. Lots of friendly folks there and @dcbriccetti is our Swing expert.

**Comment by downeym** [comment]
Newbie question here. I understand the value of having analytics be opt-out. But is there a chance for the user to opt-out at the time of initial installation/setup? Or is this feature something they'd have to stumble across by chance (or rather, through a thorough deep review of the settings)? I'd strongly encourage a UX-disruptive (interruption) chance for the user to opt out when they first use Briefcase. It would score big points for people sensitive about data privacy issues.

**Comment by jpknox** [comment]
The library I'm using has the option to disable all tracking, it would need some kind of key value to be stored in order to keep track. I could add something to the settings. I believe Briefcase asks the user for a location to store data when it starts up for the first time, I could add something there. This is all very much outside my comfort zone, and I'm very busy with others things but I can have a go.

**Comment by downeym** [comment]
Hey folks. Recognizing this is a challenging mix and that analytics are "gold" to build better software, here's a thought at how we could quickly educate users (at installation/first launch) about what we're collecting, and give them a path to opt out should they need to.

![image](https://user-images.githubusercontent.com/841003/29229297-656a313c-7e92-11e7-8d5b-c9a0c01e7500.png)

Language can most certainly be improved, and feedback on both the text and the concept is definitely welcome!

**Comment by dcbriccetti** [comment]
I like this. Not the “Can we count on you?” because it suggests that ODK would be unhappy with the user even if the user had an excellent reason to opt out. Maybe "and” instead of "&"? Is the information really anonymous? IP address?

**Comment by lognaturel** [comment]
Just to make things a little more fun, there's already a popup on first launch and, I believe, whenever the briefcase path is empty. It would be ideal if this notice could somehow be part of that existing screen (but it should only show the first time the screen is displayed).

**Comment by yanokwa** [comment]
Thanks for taking this on, all! I think the language is pretty close. Instead of `Can we count on you` we could use `Can you help`.

@jpknox, can you explore what it'd take to add something like this to the existing dialog?

**Comment by downeym** [comment]
Yeah, we have a little time to tweak the language.

I wonder if we might want to "de-scope" the opt-out process/work, and fork that into a different issue, so @jpknox can focus on just getting GA tooling in place. Don't want to add too much to his plate unnecessarily. :-)

**Comment by daveycrockett** [comment]
Agree with @downeym, I actually raised this in slack the other day (but forgot to mention it here) that I tend to favor atomic, fast and incremental issues, and opened #160 as a follow-on for the additional feature being discussed here.

**Comment by yanokwa** [comment]
Closed by #164.
