### ISSUE TITLE
Loss in connection prevents Briefcase from downloading submissions

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#152]
In Briefcase v1.6.0, pull forms from an Aggregate server where you know the number of submissions (or the number of submissions is high). (e.g., https://nafundi-test.appspot.com, login with test/test).

Turn off your connection halfway through the pull. You now have fewer submissions than the total number of submissions.

Then turn your connection back on and try to pull again. Briefcase will not download the remaining submissions. It is only after a relaunch of the app that pulling will resume.

@lognaturel believes that a UI bug that was introduced in https://github.com/opendatakit/briefcase/issues/49 and she's likely correct. I have confirmed this problem did not exist in 1.4.10.

**Comment by batkinson** [comment]
@yanokwa I noticed this behavior when I started working on 1.6.0 and it definitely seemed strange to me. However, not being a long-time briefcase user myself I figured it was just clunky UI design. I was able to track this back to 53d1f2c94. There are multiple problems with the implementation. One is that it attempts to use the status message to determine a form's activity. Another is that it assumes termination on setting a final status, yet it's not guaranteed to be set appropriately.

**Comment by lognaturel** [comment]
Yes, that's exactly right. I'm inclined to start by reverting 53d1f2c. I thought it was a marginal improvement over the double pull crash but this is more common.

**Comment by batkinson** [comment]
@lognaturel given how simple the implementation is I would say reverting is definitely a good option. Not only does it not really solve the original issue, it also doesn't seem to be symmetric with pushes. After looking at this, I think I can quickly patch it up so it addresses the original issue without causing this problem. Your call.
