### ISSUE TITLE
Upgrade Briefcase to target Java 8

### ISSUE THREAD

**Issue by daveycrockett** [opendatakit/briefcase#158]
From @lognaturel in https://github.com/opendatakit/briefcase/pull/139:

> Kind of a separate conversation but maybe we can start it here. Java 8 is about 3 years old now, could we consider targeting it? If there's an obvious reason why we shouldn't or can't without significant work then we can end the conversation here but seems worth exploring, perhaps on the dev category of the forum if there needs to be more feedback to make the decision.

Also, once this is done, LGoodDatePicker can be removed from lib/ and pulled in as a regular maven dependency.

**Comment by rockydcoder** [comment]
I think it makes complete sense to target Java 8. Oracle has already ceased public availability of security fixes and upgrades for Java 7. I am willing to take this up.
