### ISSUE TITLE
Add initial "opt-out" capability for Google Analytics tracking.

### ISSUE THREAD

**Issue by daveycrockett** [opendatakit/briefcase#160]
Related to https://github.com/opendatakit/briefcase/issues/137:

Once the above issue is merged, Google Analytics (GA) will be on by default, meaning that usage information will be sent up potentially before a user is 1) aware of it, and 2) has an option to decline.  They would need to see it "Settings" and disable it, at which point several pieces of information (OS, briefcase version, time spent on various tabs and actions taken on them prior to navigating to settings) would have been sent up.

1) Is this acceptable?
2) If not, how should the "opt-out" interaction take place on initial application load?

**Comment by yanokwa** [comment]
@daveycrockett https://github.com/opendatakit/briefcase/issues/137 now has a discussion on how to make usage tracking clearer to the user. I'm closing this issue so we can keep all the ideas in one discussion.

**Comment by yanokwa** [comment]
Re-opening so we can take a more atomic approach to the various issues involved with GA analytics.

**Comment by downeym** [comment]
From #137 ... here's my first mockup of a analytics notification. We should also discuss (here) what the process for opting out looks like, both at initial notification, and further down the line.

![image](https://user-images.githubusercontent.com/841003/29231783-573a9d6c-7e9d-11e7-823e-994e1dc8dbe2.png)

**Comment by jpknox** [comment]
From a non-GUI point of view all that must be done is call setBriefcaseTrackingConsentProperty(boolean) which is inside BriefcasePreferences.

**Comment by dcbriccetti** [comment]
I’ll renew my mild objection to:

1. the ampersands (why not “and”?)
2. “#1 easiest” (to me reads like “most easiest”)

**Comment by jpknox** [comment]
I'd like to know how to build this in Swing but my previous attempts have left me with the impression that Swing is intimidating. Does anyone have any recommendations for a particular approach or `LayoutManager` I could go for?

**Comment by dcbriccetti** [comment]
@jpknox, I wonder if this task is more challenging than would be appropriate for you at this point. You are learning quickly, but Swing is a whole other beast.

**Comment by jpknox** [comment]
@dcbriccetti That's a fair statement as I'm very busy lately studying for my PPL and buying a house, I'm not against slowing down a bit.

**Comment by dcbriccetti** [comment]
This is pretty simple to do with a JOptionPane, if we don’t need to be too fancy. Thoughts?

![screen shot 2017-08-23 at 10 13 48 pm](https://user-images.githubusercontent.com/55099/29650535-747648b0-8850-11e7-95f4-415611abc46b.png)

**Comment by lognaturel** [comment]
Does that mean it would show up after the Briefcase location window on first launch? Eventually I'd rather they be integrated but this would be fine as a first pass. Is "Cancel" the same as "No?" Seems like there should only be two options for this one!

**Comment by dcbriccetti** [comment]
I wonder whether these two initial (or one combined) dialogs are needed at all. Why don’t we just start on the Settings tab where they will have to supply a storage location before they can move to the other tabs. On that same page can be our appeal to allow usage data collection, and we can have the checkbox initially checked or unchecked.

**Comment by lognaturel** [comment]
I'm happy with that conceptually. Are you thinking something like if the location isn't set, only the settings tab can be accessed as a way of forcing it to be set?

I think the reason there was that big dialog was to provide a narrative around what Briefcase is. I think condensing that or moving it to an about menu would be ok.

**Comment by dcbriccetti** [comment]
>only the settings tab can be accessed as a way of forcing it to be set?

Yes. 

OK, I’ll proceed. This should be quick and easy. (But is *is* based on my larger Briefcase cleanup that’s still pending. I can rebase this change on master once that other change is merged.)

**Comment by dcbriccetti** [comment]
Here’s the work so far (no pull request yet): https://github.com/dcbriccetti/briefcase/tree/160-ga-opt-out
@jpknox, you’ll thank me for steering you away 😀

**Comment by jpknox** [comment]
@dcbriccetti I just took a look at the LayoutManager code your wrote and I do indeed thank you for steering me away. 😄

**Comment by downeym** [comment]
FWIW Dave's UX example LGTM. Agree on the confusion about "Cancel" though.
