### ISSUE TITLE
ExportPanel.setEnabled is brittle

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#173]
From @daveycrockett in `ExportPanel`:
```
// TODO this is brittle as the panel components change
// would prefer explicit state changes referring
// to specific components
```

**Comment by macalac** [comment]
Hi @lognaturel - would wrapping those elements from if statement into an enum be enough do you think?

**Comment by dcbriccetti** [comment]
>would wrapping those elements from if statement into an enum be enough do you think?

While it’s a good idea to use enums where appropriate, it wouldn’t address the more complicated problem here.

**Comment by macalac** [comment]
Thanks for the feedback @dcbriccetti - I will keep an eye on this to see how this can be solved.

**Comment by dcbriccetti** [comment]
I’m looking at this now. @daveycrockett, please interrupt me if you already have something going. @macalac, glad to have you follow along, review.

**Comment by macalac** [comment]
Brilliant, fastening my seat-belts!
