### ISSUE TITLE
Where should the date selection in the export tab go?

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#174]
Right now it comes after the PEM Private Key File but perhaps it should go up higher as @daveycrockett pointed out [here](https://github.com/opendatakit/briefcase/pull/139#issuecomment-322541021).

First step is to make a proposal with a justification. I don't feel strongly about it. Maybe after Export Type?

**Comment by yanokwa** [comment]
I'm closing this because I also don't feel strongly about this given the current build. I think once we add  Export Types, we can revisit this issue.
