### ISSUE TITLE
Send usage statistics shortly after user enables those settings

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#176]
In Briefcase v1.7.0-20 (and greater) usage statistics are reported on startup. This is generally fine, but when someone fires up Briefcase and toggles the statistics from off to on, it'd be good if Briefcase report those usage statistics then as well.

Not sure if this is hard or easy to do, so before sending in a PR, take a quick look at the code and respond to this issue about how hard/easy this is to do.

**Comment by yanokwa** [comment]
@jpknox This might be a good one for you to take on.

**Comment by jpknox** [comment]
@yanokwa I'll take this on :)

**Comment by jpknox** [comment]
@yanokwa Should I track this only once per session? If I track every single transition of going from 'off->on' there would be nothing stopping a user from spamming ODK's Google Analytics account.

**Comment by yanokwa** [comment]
I think you are correct, but just to be clearer about the problem I want to solve...

If the user launches the app for the first time (so the setting is off), sets the preference to on, then quits the app, we will have no idea the user ever used Briefcase. We'll only know if they launch the app again.

**Comment by dcbriccetti** [comment]
Perhaps this can be as simple as two tracking events: **Tracking Enabled** and **Tracking Disabled**. Generate one each time the checkbox changes state.

**Comment by jpknox** [comment]
I'll keep it simple to begin with and do as @dcbriccetti suggests which will satisfy your criteria @yanokwa. If there are any concerns I can address them during the PR or in the future.

**Comment by jpknox** [comment]
Thanks @dcbriccetti for the feedback; I've updated the PR, let me know if anything needs doing before I move on to the next issue.
