### ISSUE TITLE
Create setup wizard for first app launch

### ISSUE THREAD

**Issue by daveycrockett** [opendatakit/briefcase#180]
Related to https://github.com/opendatakit/briefcase/issues/160, can be implemented on top of existing work here: https://github.com/opendatakit/briefcase/pull/179

Idea would be, on first launch, that the entire application window would consist of three screens:

1) Text of MessageStrings.BRIEFCASE_WELCOME (about setting the storage area), a file chooser widget, and "next" button

2) Text of MessageStrings.TRACKING_CONSENT_EXPLANATION (plea to help the ODK community with usage stats), checkbox for opt-in/out, "next" and "back" buttons

3) Text along the lines of "Briefcase is now configured for you to begin work! <maybe a read-only confirmation of the settings selected> You can change the settings at any time from the "settings tab", "back" and "finish" buttons

Clicking finish changes the application window content to the main tabbed application panel, on the settings tab (and the above screens won't be displayed again)

**Comment by dcbriccetti** [comment]
Sounds good to me.

**Comment by lognaturel** [comment]
Très fancy!

**Comment by dcbriccetti** [comment]
I’m going to recommend we merge https://github.com/opendatakit/briefcase/pull/179 to master first. I’m almost done testing it.

**Comment by yanokwa** [comment]
Closing in favor of https://github.com/opendatakit/briefcase/issues/358
