### ISSUE TITLE
Add KML/KMZ exports to Briefcase 

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#189]
We have KML exports in Aggregate. Would be nice to offer them in Briefcase.

The KML export should probably be a KMZ export that includes the media files. To get started, 

* Document what Aggregate currently does as far as KMZ (and be sure to test with repeats, unicode, multimedia)
* Update this issue with that rough specification
* Propose how you'll implement this in Briefcase (where the code will live, any new libraries, etc)

This is similar to https://github.com/opendatakit/briefcase/issues/4.

**Comment by lognaturel** [comment]
Why is this needed? For the most part, Briefcase provides functionality that Aggregate doesn't -- backups, exports with repeats, encrypted form management. All of that makes sense to me. I worry that if there's more and more duplicated behavior it's going to be harder to understand which to use when and there'll be a risk of subtly different behavior between the two. 

Also, I thought we were going to try to move feature discussions to [the forum](https://forum.opendatakit.org/c/features) as much as possible and only have issues that are closeable in the repos? I guess we haven't properly documented this so maybe it hasn't started yet, I'm not sure.

**Comment by yanokwa** [comment]
I agree with your evaluation of the feature and the need to move these conversations to the forum. 

No one is demanding this particular feature, so I'm closing the issue.
