### ISSUE TITLE
Describe logging in contribution guide 

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#196]
Briefcase uses [Apache Commons Logging](https://commons.apache.org/proper/commons-logging/) to allow for users to use different logging implementations and configurations. This is confusing and hard to figure out for those not familiar with Java logging. The contribution guide should include a section on logging. [Spring Boot](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html) has some sections that are relevant and good models.

**Comment by lognaturel** [comment]
From Slack:
The simplest option is to use java.util.logging as the concrete implementation. You can pass in a configuration file with something like `java -Djava.util.logging.config.file=logging.properties -jar briefcase.jar`
In that `logging.properties` file you can put something like
```handlers=java.util.logging.FileHandler

.level=INFO

java.util.logging.FileHandler.pattern=.briefcase.log
java.util.logging.FileHandler.limit=50000
java.util.logging.FileHandler.count=1
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter

java.util.logging.SimpleFormatter.format=%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS.%1$tL %4$-7s %3$s %5$s: %6$s%n
```

That will log to a `.briefcase.log` file.

You can also add `java.util.logging.ConsoleHandler` to the handlers list or exclusively use that.

I don't know where to find docs for the config file. https://gist.github.com/vanting/2049648 is pretty good.

**Comment by batkinson** [comment]
> The simplest option is to use java.util.logging 

This is the simplest from the standpoint of dependencies, but as you can see once the google analytics library was added to briefcase it isn't a complete solution. Most of briefcase's important information is logged over other frameworks already. Also, you won't be able to change third-party library code to use JDK logging in order to unify them. The way to do this without forking all your dependencies is to use SLF4j. See #204

**Comment by batkinson** [comment]
If #204 or something like it is integrated, you can configure the slf4j simple logger using these options:

https://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html

**Comment by lognaturel** [comment]
Will update the issue to reflect the new state of things once I get a couple of clarifications at https://github.com/opendatakit/briefcase/issues/197#issuecomment-332197461

**Comment by yanokwa** [comment]
@ggalmazor Now that we have an updated logging configuration, this might be a good PR for you to send in.
