### ISSUE TITLE
Extend command line interface to match graphical user interface

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#20]
Currently, Briefcase's command line interface only allows for pulling data from ODK Aggregate. It would be great to have support for also pushing data to servers.

**Comment by shivam-tripathi** [comment]
I would like to work on this.

**Comment by yanokwa** [comment]
@shivam-tripathi As a first step, can you please draft up a quick proposal listing what exists in the CLI and what needs to be added from the UI? For each addition, detail the flags you expect to use.

**Comment by shivam-tripathi** [comment]
![table_flags](https://cloud.githubusercontent.com/assets/9463078/25342016/574f83d2-2928-11e7-8c8b-c66c072724f0.jpeg)
Presently, there is no specific option to specify if the operation intended is "Extraction" or any other. _Push_ is one of the basic operation, apart from _Pull_ and _Extraction_. 
For _Pull_ operation, only a single operation would be needed to specify that the operation intended is pulling. Same goes for extraction. Perhaps something like "-pull" and "-e" would serve the purpose.
Another thing to be considered is change in assigned flags. Does "p" flag best assigned to password?
Also, another thing I noticed is argument name assigned to flag "f" is "name.csv". In future we might be supporting more options than just csv for export. Maybe we should change the name. Should I open an  issue for this?

**Comment by shivam-tripathi** [comment]
@yanokwa

**Comment by yanokwa** [comment]
@shivam-tripathi This is a great first start! 
* I think having some action flag would be a good idea. I think I'd have --action {pull,push,export} or something along those lines.
* I think p for password is pretty good. What's your concern? You want to use it for pull?
* Agreed that we might want to export other formats, so having an export type would be pretty nice.  Please open an issue for this!
* The ability to export a date range is something that's in the CLI but not in the GUI. Can you please open an issue for this too?
