### ISSUE TITLE
Provide option to overwrite on export in GUI

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#202]
As described in https://forum.opendatakit.org/t/duplicates-on-exporting-via-briefcase/9879

The option to overwrite an existing export is provided by the `-oc,–overwrite_csv_export` flag in CLI mode and should be surfaced in the UI.

@yanokwa @daveycrockett you will probably have ideas on where this should go. We should get agreement on that before it gets built!

**Comment by daveycrockett** [comment]
Perhaps a dialog that says "The file already exists. Overwrite? Y/N"

**Comment by lognaturel** [comment]
@nribeka I know you're looking for an issue to take on and this could be a good one? The challenge is figuring out the UI and really thinking it through before building. @daveycrockett's suggestion is a good one but I worry that for people who need to do periodic exports they'd be too likely to accidentally overwrite the file they intend to build up.

How about a checkbox that says something like "Overwrite existing" and is unchecked by default. If the user checks it, then there's a confirmation dialog like the one @daveycrockett suggested but with ok/cancel instead. Just an idea, this will require some more thought. @rockydcoder and @dcbriccetti also have good UI ideas.

**Comment by fabla** [comment]
@lognaturel I think i love this idea. "How about a checkbox that says something like "Overwrite existing" and is unchecked by default"

it will be pretty cool.
Thanks

**Comment by lognaturel** [comment]
Thanks @fabla, that's useful feedback! @ggalmazor this would be a good one to also think about as you rework that export tab.

**Comment by ggalmazor** [comment]
OK! A simple checkbox that says "Overwrite existing files", unchecked by default, sounds simple and easy to use. 

After the work we have done on the export tab, I think anyone could contribute doing this one. Just check `ExportConfigurationTest`, `ExportPanel` (line 175) and `ExportAction.export(...)` method.

**Comment by ggalmazor** [comment]
@opendatakit-bot label "quick win"
@opendatakit-bot label "contributor friendly"

**Comment by ggalmazor** [comment]
@opendatakit-bot unclaim

**Comment by ggalmazor** [comment]
@opendatakit-bot unlabel "quick win"

**Comment by emajj** [comment]
@opendatakit-bot claim

**Comment by emajj** [comment]
Is the UI code auto-generated or is it hand coded? I've located this file ConfigurationPanelForm which I believe is where I have to add the new UI components but I noticed at the bottom there's a generated code

 ```
 /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    container = new JPanel();
    container.setLayout(new GridBagLayout());
    exportDirLabel = new JLabel();
    exportDirLabel.setText("Export directory");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.anchor = GridBagConstraints.EAST;
    container.add(exportDirLabel, gbc);
    pemFileLabel = new JLabel();
    pemFileLabel.setText("PEM file location");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.anchor = GridBagConstraints.EAST;
    container.add(pemFileLabel, gbc);
    startDateLabel = new JLabel();
    startDateLabel.setText("Start date");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.EAST;
    container.add(startDateLabel, gbc);
    endDateLabel = new JLabel();
    endDateLabel.setText("End date");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 3;
    gbc.anchor = GridBagConstraints.EAST;
    container.add(endDateLabel, gbc);
    exportDirField = new JTextField();
    exportDirField.setEditable(false);
    exportDirField.setName("exportDir");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(exportDirField, gbc);
    pemFileField = new JTextField();
    pemFileField.setEditable(false);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.weightx = 1.0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(pemFileField, gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 2;
    gbc.gridwidth = 2;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(startDatePicker, gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 3;
    gbc.gridwidth = 2;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(endDatePicker, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(spacer2, gbc);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(spacer3, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 3;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(spacer4, gbc);
    pullBeforeField = new JCheckBox();
    pullBeforeField.setText("Pull before export");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 5;
    gbc.gridwidth = 2;
    gbc.anchor = GridBagConstraints.WEST;
    container.add(pullBeforeField, gbc);
    pullBeforeHintPanel = new JTextPane();
    pullBeforeHintPanel.setAutoscrolls(false);
    pullBeforeHintPanel.setEditable(false);
    pullBeforeHintPanel.setFocusCycleRoot(false);
    pullBeforeHintPanel.setFocusable(false);
    pullBeforeHintPanel.setOpaque(false);
    pullBeforeHintPanel.setText("Some hint will be shown here");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 7;
    gbc.gridwidth = 2;
    gbc.fill = GridBagConstraints.BOTH;
    container.add(pullBeforeHintPanel, gbc);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 6;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(pullBeforeOverrideField, gbc);
    final JPanel spacer5 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 4;
    gbc.gridwidth = 3;
    gbc.fill = GridBagConstraints.VERTICAL;
    container.add(spacer5, gbc);
    pullBeforeOverrideLabel = new JLabel();
    pullBeforeOverrideLabel.setText("Pull before export");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 6;
    gbc.anchor = GridBagConstraints.WEST;
    container.add(pullBeforeOverrideLabel, gbc);
    exportDirButtons = new JPanel();
    exportDirButtons.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.BOTH;
    container.add(exportDirButtons, gbc);
    exportDirCleanButton = new JButton();
    exportDirCleanButton.setText("Clear");
    exportDirCleanButton.setVisible(false);
    exportDirButtons.add(exportDirCleanButton);
    exportDirChooseButton = new JButton();
    exportDirChooseButton.setText("Choose...");
    exportDirChooseButton.setVisible(true);
    exportDirButtons.add(exportDirChooseButton);
    pemFileButtons = new JPanel();
    pemFileButtons.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.BOTH;
    container.add(pemFileButtons, gbc);
    pemFileClearButton = new JButton();
    pemFileClearButton.setText("Clear");
    pemFileClearButton.setVisible(false);
    pemFileButtons.add(pemFileClearButton);
    pemFileChooseButton = new JButton();
    pemFileChooseButton.setText("Choose...");
    pemFileChooseButton.setVisible(true);
    pemFileButtons.add(pemFileChooseButton);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return container;
  } 
```
So I was wondering if there's a specific drag and drop tool we used to design the UI.

**Comment by ggalmazor** [comment]
Hi @emajj! That particular class is half auto-generated, half written by hand. 

You will see that some java files have a "twin" file with `.form` extension. These files are to be changed with IntelliJ's UI Designer plugin (make sure you have the plugin installed and double click to see a WYSIWYG visual editor).

When you make changes to the UI, the corresponding `$$$setupUI$$$` method in its twin `.java` file is updated. You should never manually change `$$$getRootComponent$$$` or `$$$setupUI$$$` methods. The rest of the file is safe to change.

The workflow here is to start with the UI Designer working on a component's visual parts and then start writing code on the constructor to add listeners, etc., or adding methods to let other objects interact with it. A good example is the `ConfigurationPanel` component and its `ConfigurationPanelForm` view. We are trying to make Swing code as much Model-View-Controller as we can.

**Comment by emajj** [comment]
Thanks @ggalmazor for the explanation. Using the designer, I added a checkbox on ConfigurationPanelForm.form for overriding existing files. An instance variable was created in ConfigurationPanelForm.java called overwriteExistingFilesCheckBox. But the $$$setupUI$$$ method was not modified so my instance variable is not initialized and not been added to the UI programmatically even though the checkbox is been shown by the designer. Is there something I need to do for that to happen?

**Comment by ggalmazor** [comment]
If you build the project, the setup method should update with the new field initialization. Make sure the option for custom cretion is not checked on the UI Designer.

**Comment by emajj** [comment]
I have built using ./gradlew clean build -x  test and also built using idea Build Project and the $$$setupUI$$$ method is still not been updated. Below is how my form looks like. Not sure where to check for custom creation checkbox.

![image](https://user-images.githubusercontent.com/36533836/36657728-f6ba9730-1acd-11e8-9fb5-4c9f60afef8e.png)

**Comment by ggalmazor** [comment]
Hi @emajj!

![image](https://user-images.githubusercontent.com/205913/36659166-cbab5196-1ad3-11e8-8b50-62640b64ca2e.png)

If the checkbox highlighted on the left is not checked, after building with button highlighted on the top you should see changes on the setup method.

**Comment by emajj** [comment]
Hi @lognaturel @ggalmazor I will need some clarity on the solution proposed here. When I first read @lognaturel comment I assumed this task involves adding a checkbox that will be unchecked by default then when the user checks it a dialog will appear warning/informing them that they will be overwriting existing files. So I understood that this means only one dialog will be show and that is when the user checks the overwrite existing files option as shown in the screenshot below  

![screenshot_2018-02-26_16-28-46](https://user-images.githubusercontent.com/36533836/36678872-27ce206e-1b12-11e8-89e7-22281abc5b29.png)

But reading the comment now again makes me feel like I thought of it wrong. It seems the idea is that, when the checkbox is checked, during the import, a dialog will be shown on every existing file asking the user if they want to overwrite this file. That is, if there are 20 existing files then the dialog will be shown 20 times before overwriting each one. Is this correct? 

Notice in the first case, the dialog is shown even before the export is started while in the second case the dialog is shown when the export has already started and an existing file is found.

**Comment by ggalmazor** [comment]
I think 1 confirmation dialog when the user checks the option is what makes most sense. 

Showing an alert for each overwritten form is not practical in my opinion

**Comment by lognaturel** [comment]
This issue was created before multiple exports so I was imagining a confirmation when the export was started and an export csv already existed. 

@ggalmazor is right that multiple dialogs would be annoying. How about having one dialog when the export is triggered with a list of the files that will be overwritten (if any)? For example:

Export will overwrite these existing files:
- cool-form.csv 
- my-export.csv

Continue?

**Comment by lognaturel** [comment]
Good point about media files, repeats, etc. How about:
Export files exist for the following forms:
* My Cool Form
* My Export
Overwrite?

We can certainly do this in a separate issue.

**Comment by ggalmazor** [comment]
Alright, looks like a plan.

@emajj, let's go for a simple confirm dialog that will pop up whenever the user checks that setting (on the default conf panel **and** on every override conf panel).

We'll file a separate issue to improve this by implementing what @lognaturel has described:
> How about if the main CSV exists for a form, the form name is included in the dialog:
>
> Export files exist for the following forms:
>
>  - My Cool Form
>  - My Export
>
> Overwrite?

**Comment by yanokwa** [comment]
To me, it'd be annoying to get a dialog asking me to confirm something that I've explicitly asked the system to do. How strongly do you feel about the dialog, @ggalmazor/@lognaturel?

**Comment by ggalmazor** [comment]
I think that it would help to ask for confirmation (at least once) when the user checks a setting that might get data deleted.

We could work on this following this progression:
1. The confirm dialog appears everytime a user tries to check the overwrite conf (both in the default and override conf panels).
2. We improve this to make the dialog appear just once. We can save on preferences we've already shown the confirm dialog to the user.
3. We make the dialog better by showing what's going to be overwritten.

I don't see any major problems to implement 1 and 2 on this PR but I think it's important to have "escape routes" to use if we get in trouble.

Even if we only manage to get into this PR number 1, best case scenario, the user only sees 1 confirm dialog when she check the override conf in the default conf panel and she never sees it again.

**Comment by yanokwa** [comment]
I think this is a smart approach. Does this sound reasonable to you, @emajj?
