### ISSUE TITLE
Log to a briefcase.log file by default

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#210]
**#209 needs to be done first** so command-line mode isn't broken.

Provide a default configuration to the SLF4J simple binding so errors are logged to a `briefcase.log` file. This will make it easier to troubleshoot user problems. I propose making the filename `briefcase.log` rather than `.briefcase.log` so it's easy for users to look at and share if needed.

In #197 I had proposed logging at level `INFO` but I think that will be too much. I think `WARN` should provide sufficient information.

This will involve placing a file named `simplelogger.properties` in the `res` directory.
```
# Log to a file at log level WARN
org.slf4j.simpleLogger.logFile=briefcase.log
org.slf4j.simpleLogger.defaultLogLevel=warn
```

**Comment by ggalmazor** [comment]
I think this issue could be closed. After #356, this is something that needs to be taken care of during the release process.
