### ISSUE TITLE
ParserConsts needs a private constructor

### ISSUE THREAD

**Issue by rockydcoder** [opendatakit/briefcase#213]
This is not an issue with the functionality but more of a good practice. `ParserConsts` being a final class with static members only, needs to have a private constructor so it cannot be instantiated.

**Comment by ggalmazor** [comment]
Also, clean unused members?

**Comment by ggalmazor** [comment]
@opendatakit-bot label "quick win"

**Comment by dsukmanova** [comment]
@rockydcoder @ggalmazor 
Hello! I want to participate in Outreachy program and looking for issues in this project. Can I take this one or you recommend some others?
Thanks

**Comment by ggalmazor** [comment]
Hi @dsukmanova! It's great you want to participate, thanks! Before starting to take issues, it's really important you pass the eligibility tests for the project you want to apply. You can check all the information here: https://www.outreachy.org/communities/cfp/open-data-kit/

**Comment by dsukmanova** [comment]
@ggalmazor I've already did it (if you mean eligibility tests for Outreachy program)

**Comment by ggalmazor** [comment]
Yes, I was telling you that because I can't see you have applied for any of the projects yet.

In any case, you can claim this issue adding a comment with `@opendatakit-bot claim` :)

**Comment by dsukmanova** [comment]
@opendatakit-bot claim
