### ISSUE TITLE
Use minimum scope for members throughout the code base

### ISSUE THREAD

**Issue by rockydcoder** [opendatakit/briefcase#214]
Many members of classes have the improper/no access modifier set. It is always a good practice to use the minimum scope for these.

**Comment by ggalmazor** [comment]
Also, clean unused members, maybe? :)

**Comment by ggalmazor** [comment]
@opendatakit-bot label "quick win"

**Comment by macdude357** [comment]
I assume you are referring to code like this example:

https://github.com/opendatakit/briefcase/blob/0cc67e90b80fa92649ebc586f8b6b556bf1861ad/src/org/opendatakit/aggregate/form/XFormParameters.java#L30

In those cases, I assume you want to change that to private and add getters/setters if any other class is accessing those members directly?

**Comment by ggalmazor** [comment]
That's right. More specifically, I think I'd expect IntelliJ's inspections to tell me which members (fields and methods) can have a reduced scope, and which one in each case.
