### ISSUE TITLE
Server settings should persist between restarts

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#22]
It's pretty annoying to retype server settings on application restart. Server settings (both for pull and push) should persist across restarts.

**Comment by carstendev** [comment]
I´d like to pick this up, I found it to be really annoying as well.

**Comment by carstendev** [comment]
@yanokwa Should the user password also be persisted? If so, I would have to do that using a two-way encryption algorithm. Doing so, we could not guarantee, that the password is a 100% safe, from decryption by an unauthorized person with access to the users machine.

**Comment by yanokwa** [comment]
@carstendev Excellent question! I don't know of a secure and cross-platform way of storing passwords locally. Given that, I think the safest thing to do is not to store the password.

**Comment by mitchellsundt** [comment]
You might want a generic shared list of the last N servers accessed, and then also store within each Briefcase Storage Location the URL for the server that was last accessed in that storage location.  Not sure how people use the tool -- should there be just one URL -- whichever was used for either Pull or Push, or should there be different values for the last server Pull'd and the last server Push'd.

This allows the "default" to stick and travel with the storage location (e.g., if you zipped it up and sent it to someone), and if you had multiple storage locations, or needed to create a fresh one, you would have the global list on that computer from which to select a URL.

**Comment by yanokwa** [comment]
I would guess that push is generally not used, and when it is, it is used to migrate data between servers or to push data that is pulled from Collect to some server. Both those scenarios would likely require separate servers. Additionally, those modes are clearly separated in the UI and keeping the URLs separate maintains that separation. For these reasons, I think pull and push servers should be different.

I think the preferences should be persisted to wherever Java persists preferences for now because I don't know many people who actually shuffle Briefcase folders around. Is that a use-case you've seen often, @mitchellsundt?

**Comment by carstendev** [comment]
Okay @yanokwa, from what I can gather, we want the preferences for push and pull to be separately managed. Now should they be global, or managed per Briefcase Storage Location?

**Comment by yanokwa** [comment]
Let's go with global for now.
