### ISSUE TITLE
Briefcase should run on Java 9 machines

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#220]
Verify that Briefcase works with Java 9 (JDK and JRE). If it doesn't, then suggest a fix!

**Comment by icemc** [comment]
@opendatakit-bot claim

**Comment by yanokwa** [comment]
@opendatakit-bot label "needs discussion"

**Comment by yanokwa** [comment]
@opendatakit-bot unlabel "needs discussion"

**Comment by yanokwa** [comment]
@kkrawczyk123 can you please take a look at this issue? I'm particularly interested to see if you can pull and export an encrypted file on all three OSes with Java 9 installed.

**Comment by kkrawczyk123** [comment]
@yanokwa I tried to figure it out but I am a bit blocked with that. Do you want me to update java version and then build or update java, change java version in project and then build?. When I tried first approach build has failed on all three systems with the same error message. What is the best way to investigate that issue?

**Comment by yanokwa** [comment]
I'd recommend you build it on a machine running Java 8 (OS shouldn't matter). You can build with `.gradlew clean jar` or grab the latest binary from [CircleCI](https://github.com/opendatakit/briefcase#downloading-builds)

Then take the build and run it on machines running Java 9 and see if they work.

**Comment by kkrawczyk123** [comment]
I tried both, building on machine running Java 8 with using command that you mentioned (on mac), then running on machine with java 9 (windows) and also tried to grab it straight from CircleCI and run with java 9. In both cases running briefcase failed. Screenshot attached.
![java windows](https://user-images.githubusercontent.com/33342488/35093290-46849018-fc42-11e7-92ed-5bceb5580e02.jpg)

**Comment by yanokwa** [comment]
Thanks for the detailed report, @kkrawczyk123! 

@ggalmazor Can you take a look to see if this is easy to fix?

**Comment by ggalmazor** [comment]
Sure!

**Comment by ggalmazor** [comment]
Turns out that the Eclipse's jar-in-jar loader we're using doesn't work with Java9.

I'm exploring alternatives and everything I'm finding is already 5 or 6 years old :|

We'll have to dig deeper in this one...

**Comment by yanokwa** [comment]
The thing that's complicated about packaging jars in Briefcase is that we can't explode the jars because BouncyCastle is signed and that'll break encrypted exports. 

From https://github.com/eclipse/eclipse.jdt.ui/commit/b0d91c8941ed71dd31d4e8fe17e643b5caa5ec41 it seems like there is support for in Eclipse for Java 9 now. 

Maybe you can try building that one, or grabbing the binary from https://git.eclipse.org/c/jdt/eclipse.jdt.ui.git/plain/org.eclipse.jdt.ui/jar-in-jar-loader.zip and seeing if it has the updated changes.

**Comment by ggalmazor** [comment]
I'm afraid that the new version of the same loader won't work out of the box... The reason is explained [here](http://java9.wtf/class-loading/)

I'll try to patching it...

**Comment by ggalmazor** [comment]
Good news: Patching the loader works
Bad news: We have to maintain this now
Worse news: We will have to produce a separate JARs, one for Java8 and other for Java9

Best case scenario, we can file an issue on Eclipse with the patch and wait for them to release a patched version of the loader...

**Comment by ggalmazor** [comment]
I have yet to rule out jlink, though

**Comment by yanokwa** [comment]
I don't know if we want to spend too many cycles on this. 

Since you have a patch, I propose we send it upstream to Eclipse so we can be good open source citizens. They also might have an approach that works better and it'd be good to get their feedback.

Then if you have other ideas (e.g., jlink) create an issue with a rough approach and we'll if a contributor wants to take it on.

In the short term, we can just say users should use Java 8.

**Comment by ggalmazor** [comment]
Ok!

**Comment by ggalmazor** [comment]
So, I did my homework and I'm waiting for permission to push the patch into their repo. Here is the bug report: https://bugs.eclipse.org/bugs/show_bug.cgi?id=529172

In the meantime (thanks to other contributor's comments there), I've managed to prepare a solution that will compile and run both in Java8 and Java9. We can add that to Briefcase and remove whenever Eclipse updates their loader.

I have everything ready and tested for a PR should we want to proceed with this.

As a sidenote, I'm quite happy about our contribution process. I recon that we're not Eclipse, but their process is quite convoluted. Using tools like Github and Slack is much more simpler. I don't know how well would scale to an Eclipse sized project, though.

**Comment by yanokwa** [comment]
This is great news, @ggalmazor! Let's wait a few more days to see if they have any feedback on the patch. If we don't hear back by code freeze day, then we can ship our version.

As far as contribution process, yeah, we aren't too bad. @lognaturel did a great job making that process super simple.

**Comment by ggalmazor** [comment]
Ok, I don't fully understand what's going on but it seems that my changeset  has been approved by my reviewer and now there is a second changeset that (I think) is the one that will be merged to master. They have mentioned some merge to an M5 version and a backport to version 4.7.3 but I've asked what all this means in terms of release of a new version...

**Comment by ggalmazor** [comment]
Changes are merged in master, yay! Now I'm filing another changeset to update the zip file :)
