### ISSUE TITLE
Replace user facing ODK Aggregate 1.0 text with ODK Aggregate

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#228]
We use "Aggregate 1.0" in the user-facing sections of ODK Briefcase and it's a bit of a misnomer. 

"Aggregate 1.0" is a stand-in for any server that implements the OpenRosa 1.0 API. To users, this basically means ODK Aggregate v1.x. For consistency with ODK Collect, I'd propose replacing the GUI parts of ODK Briefcase that say "Aggregate 1.0" with "ODK Aggregate". I'd also be OK with "ODK Aggregate 1.x"

This came to mind because we've removed all 0.9.x from the code (https://github.com/opendatakit/briefcase/issues/200).

**Comment by nribeka** [comment]
I think this would depends on Aggregate naming convention. Will there be a lot of 1.x releases or is it going to be just called Aggregate 1 and then the next release is Aggregate 2.

**Comment by yanokwa** [comment]
We use [sem ver](https://semver.org/) so there are going to be more 1.x releases. Maybe we should call it "ODK Aggregate" until there is actually a 2.x then change it then.

**Comment by icemc** [comment]
@opendatakit-bot claim
