### ISSUE TITLE
Replace dialogs from CLI with command line messages

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#237]
It's pretty unusual for a command line interface to have dialogs...

**Comment by rockydcoder** [comment]
I would like to take this up. @lognaturel , can you add some more description please?

**Comment by lognaturel** [comment]
If you look at the `BriefcaseCLI` class, you'll see that there are some dialogs being generated and shown! That's highly unusual for a command line interface. That feedback should go to `system.err` in the case of an error and `system.out` in the case of a notice.

**Comment by lognaturel** [comment]
I also encourage you to look at #234 and #218 which are related to improving the command line interface.

**Comment by rockydcoder** [comment]
@opendatakit-bot claim
