### ISSUE TITLE
Improve how Briefcase deals with high-dpi displays

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#241]
See https://github.com/opendatakit/validate/issues/45

**Comment by yanokwa** [comment]
According to https://forum.opendatakit.org/t/-/10638/4 upgrading to Java 9 solves the problem. It would be good to confirm, then update the docs.

**Comment by yanokwa** [comment]
@opendatakit-bot unclaim

**Comment by yanokwa** [comment]
@opendatakit-bot claim

**Comment by yanokwa** [comment]
@opendatakit-bot unclaim

**Comment by lognaturel** [comment]
I thought this had been resolved?

**Comment by yanokwa** [comment]
Not really. According to https://forum.opendatakit.org/t/-/10638/4 upgrading to Java 9 solves the problem. It would be good to confirm, then we can update the docs.

**Comment by ggalmazor** [comment]
Could we check this, now that Briefcase runs on Java9?

**Comment by yanokwa** [comment]
Confirmed fixed.
