### ISSUE TITLE
There is active "Export Details..." button without any exporting activity.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#247]
#### Software versions 
Briefcase v1.8.0, Java v1.8.0_151, operating system - Ubuntu

#### Problem description
There is active "Export Details..." button without any exporting activity.

#### Steps to reproduce the problem
1. Go to Export section.
2. Click on "Export Details..." button.

#### Expected behavior
"Export Details..." button should be active only after exporting forms, when There are some details to display.

#### Other information 
If you click on "Export Details..." button without previous form export nothing will really happen it will just deactivate that button.

**Comment by ggalmazor** [comment]
With latest PR activity, this shouldn't happen anymore, could you check again, please?

**Comment by kkrawczyk123** [comment]
Yes, it seems to be fixed.

**Comment by ggalmazor** [comment]
Yay! Thanks!

**Comment by yanokwa** [comment]
Confirmed fixed in 32d6499.
