### ISSUE TITLE
Briefcase doesn’t pull data from mounted Android SD Card from device without SD card inside.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#251]
#### Software versions 
Briefcase v1.8.0, Java v1.8.0_151, operating systems - Ubuntu 17, Windows 7 

#### Problem description
You are not able to pull data from ODK Collect when device that you are using doesn’t have SD card. Briefcase simply doesn’t see that device and doesn’t consider device’s internal storage as a memory that it can pull data from.

#### Steps to reproduce the problem
1. Fulfill forms on ODK Collect app on mobile device without SD card.
2. Connect your device to computer with installed Briefcase.
3. Choose Mounted Android SD Card option in Pull data from section.
4. Try to choose SD Card.

#### Expected behavior
Briefcase should consider internal storage of device as a SD card and be able to pull data from all Android mobile devices. 

#### Other information 
Most of new mobile phones don’t even have place to put SD card into that.

**Comment by kkrawczyk123** [comment]
You can pull data from Collect from all Android devices by using option Custom Path to the ODK Directory.

**Comment by lognaturel** [comment]
@kkrawczyk123 do you feel like this is adequately documented at http://docs.opendatakit.org/briefcase-forms/#pulling-from-android-4-x-and-later-device? If you think that could be improved, consider filing an issue at https://github.com/opendatakit/docs/issues
