### ISSUE TITLE
Rethink pull_aggregate short form

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#256]
It's currently -pa but we'll eventually want to be able to push to Aggregate from CLI as well. How do we differentiate between the two since they both start with p?

**Comment by jpknox** [comment]
Maybe -psha or -plla?

**Comment by lognaturel** [comment]
Good suggestions, @jpknox. The existing "short forms" aren't that short so those would fit in.

@ggalmazor @yanokwa?

**Comment by ggalmazor** [comment]
Just realized that we could also make a compound command with `-pull -a` and `-push -a`.

`-a` would server to indicate that we want to make an operation against an Aggregate server. It could also be `-agg`, etc.Then we could have other `-odk` or `-sd` flag to tell Briefcase to go to an sd card folder, etc.

**Comment by yanokwa** [comment]
I think we can keep `-pa` for backwards compatibility (but warn about deprecation) and introduce `-psha` and `-plla` when we add push from the CLI. It doesn't really make sense for Briefcase to push to an SD card for Collect, but `pshc` would work nicely there.

We need to do a refactor of pull first, then push, then we can add CLI support. Does that plan sound reasonable, @ggalmazor? Do you want to keep this issue open until then or should we close it?

**Comment by ggalmazor** [comment]
OK, sounds good.

If you want these changes on different PRs, we can add a checklist on the main comment to track progress.
