### ISSUE TITLE
The text area in the Details... dialog should not be editable

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#26]
#### Software and hardware versions 
ODK Briefcase v1.4.9 Production, Java 1.8.0_25, MacOS 10.12.1

#### Problem description
The text area in the `Detailed Transfer Status for [form]` dialog is editable.

#### Steps to reproduce the problem
1. Connect to a server with forms.
1. Click on a form's `Details...` button.
1. Type in the `Detailed status` text area.

#### Expected behavior
The text area should not be editable.

**Comment by carstendev** [comment]
Working on this.
