### ISSUE TITLE
Folder selection behavior is odd

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#261]
In the master build of Briefcase, here's the behavior I'm seeing in Export Directory on macOS. 

If I'm "in" the Desktop folder, Open should select that folder. Instead, I have to be in my Home folder and before I can select the Desktop folder. This only happens when Export Directory is blank. When it's not, I can be in a folder and select it.

![select-folder](https://user-images.githubusercontent.com/32369/34614160-5663b8ea-f1e5-11e7-8da4-fbeff5a7153b.gif)

@ggalmazor reports that this doesn't happen on Linux, which suggests it might be a platform-specific bug.

@kkrawczyk123 everywhere in Briefcase where is a selection for a folder or file (Export DIrectory, PEM Private Key File, Storage Location), can you try the master build on Ubuntu, macOS, and Windows and report back what you find? Both when the selection is a folder and when it is a file.

**Comment by ggalmazor** [comment]
Hi! Just tried this on Linux and Mac and I have confirmed that the file dialog's behavior in Mac and Linux is not the same:

 - Linux: clicking on "OK" button without selecting any item won't do anything (the dialog stays open)
 - Mac: clicking on "Open" button without selecting any item will close the dialog and give back control the parent window.

I will try to prepare a workaround.

**Comment by kkrawczyk123** [comment]
On all three systems I verified selection of folders and changing it. I didn’t find anything suspicious. I checked Export Directory and Storage location. If it is about PEM Private Key File I didn’t have that kind of file but I tried just to choose file and I was able to select there any .csv files, I am not sure if that approach is enough. @lognaturel , @yanokwa  could you attach me some PEM Private Key File and encrypted form? It could be also useful in future. As I’ve already mentioned in [#259](https://github.com/opendatakit/briefcase/pull/259), on Linux and Windows I couldn’t select “OK” without choosing any location. I tried to investigate issue that @yanokwa  found on Mac, I didn’t succeed in reproducing it, but my results was like @ggalmazor , I didn’t have option to choose none location on Mac, if I clicked on “OK” without picking any folder, on Export directory was saved previous location that was chosen, so Mac considered it as default one. I was able to choose Desktop location everytime I tried, no matter if Export Directory was blank or not.

**Comment by ggalmazor** [comment]
Thanks, @kkrawczyk123!!

Regarding the PEM file, for the purpose of testing the changes on the file selection dialogs, it doesn't matter that the file is really a PEM file or not. Any file will let you test the behavior.
