### ISSUE TITLE
suggestion for briefcase UI

### ISSUE THREAD

**Issue by NaderBeshr** [opendatakit/briefcase#269]
i was thinking in new ui for briefcase. i think if we use color and graphic symbols will be easier for users. so i share my thought with all of you.

![0ca82861884e6df9d7bdd9f5ef9437b27444e953_1_366x500](https://user-images.githubusercontent.com/3519285/34918808-585779fc-f96a-11e7-9c2c-6fe669c5491f.jpg)

**Comment by yanokwa** [comment]
Thanks for sending in this @NaderBeshr! 

I'm closing the issue because we can't take this on in the foreseeable future. When we have the cycles for a UI rework, we'll re-open this issue and discuss at that time.
