### ISSUE TITLE
Form-level export configuration icon not shown on Mac

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#270]
#### Software versions 
Briefcase v1.8.0-113-g50d5b8d9, macOS 10.13.2

#### Problem description
The gear icon doesn't appear
![](https://user-images.githubusercontent.com/55099/34911141-6407003a-f878-11e7-8b4b-05edb1528378.png)

#### Steps to reproduce the problem
Launch the application from macOS, go to the export tab.

#### Expected behavior
The gear icon should be visible.

**Comment by yanokwa** [comment]
Closed by #294.
