### ISSUE TITLE
Add coverage report

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#277]
Now that we're starting to have some tests, it would be helpful to have some metrics about code coverage.

This information would be also helpful on CircleCI

**Comment by lognaturel** [comment]
@shobhitagarwal1612 had added a jacoco/Codecov integration over on the Collect side. It worked really well and is only disabled now because integration tests were moved to run on Firebase. Should we go with the same here?

**Comment by ggalmazor** [comment]
:+1: I know Jacoco from other Java8 projects and it does the work.

**Comment by yanokwa** [comment]
I had a PR for codecov, but deleted it because I find the UI a bit klutzy. I was thinking maybe we'd give codeclimate a try? https://codeclimate.com/github/opendatakit/briefcase/
