### ISSUE TITLE
Global export preferences are not persisted on clear

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#286]
In the global export settings of master (3b29d73ad7c688276eccb44f463fe0fb64395494), if PEM file location or start/end date is cleared, that clearing is not persisted. If I relaunch the app, the value  still exists. If instead I change the value, that value is persisted.

**Comment by ggalmazor** [comment]
I've already done some work related to this behavior (on custom confs) on PR #281 and I have extended the PR to solve this issue as well.

**Comment by yanokwa** [comment]
Fixed by #281
