### ISSUE TITLE
Long export paths in custom configuration lead to very wide window

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#291]
If you try to export to a very deep path, the export configuration window gets wider and wider.

<img width="1118" alt="screen shot 2018-01-23 at 11 09 03" src="https://user-images.githubusercontent.com/32369/35295482-2374a3e8-002e-11e8-8263-b7a698330c1e.png">

 I'm not sure how other Java UIs do this (@dcbriccetti, you might know), but I'd be nicer if there was some maximum width where we truncate the beginning of the path. This is how we do it on the global export directory.

<img width="605" alt="screen shot 2018-01-23 at 11 11 39" src="https://user-images.githubusercontent.com/32369/35295547-3e19a27a-002e-11e8-8f08-659fe12ca879.png">

**Comment by dcbriccetti** [comment]
Maybe set a preferred and/or maximum size on that control, and/or elide parts of the path.

**Comment by ggalmazor** [comment]
Yes, I can copy that property from other fields that cap the max width

**Comment by yanokwa** [comment]
And we can make that initial dialog window a little wider to make start. It looks like it's about 60% of the main window and we could do 75-80%.

**Comment by dcbriccetti** [comment]
Its width is defined by the preferred sizes of its components.

**Comment by ggalmazor** [comment]
I can make a quick fix for the dialog's size setting a preferred width for the fields that will produce a dialog almost (or even exactly) as wide as the main window, before packing the dialog.

Regarding the wide export dir field on the default configuration, I don't know if I can do both things: making the field expand to fill the horizontal space and, at the same time, cap its width. 

Maybe by setting the cap to the main window will work...

**Comment by dcbriccetti** [comment]
I don’t see why we should be concerned about the size of the dialog in relation to the size of the main window.

**Comment by ggalmazor** [comment]
The bottom line is that if we want, we can have a wider dialog :P
