### ISSUE TITLE
Differences in Export section UI between Ubuntu and MacOS.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#298]
#### Software versions 
Briefcase v1.8.x, Java v1.8.x, operating system: Ubuntu, MacOS

#### Problem description
There is a difference in view of override export configuration button. The button is displayed on ubuntu but on macOs it looks like an empty button (it works properly if you click on it).

#### Steps to reproduce the problem
1. Open export on ubuntu and on macOS.

#### Expected behavior
I guess it should look in the same way.

#### Other information 
Screenshot of difference attached. 
![export form](https://user-images.githubusercontent.com/33342488/35336334-620bbea8-0118-11e8-9a78-cd8828ebb72d.png)
![export form_mac](https://user-images.githubusercontent.com/33342488/35336383-7dff05e8-0118-11e8-908d-2154e4afeb92.png)

**Comment by yanokwa** [comment]
Closed in favor of #270
