### ISSUE TITLE
CLI short codes are not backwards-compatible

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#304]
The code on master changes several short codes:
`-id,--form_id <form_id>` => `-f,--form_id <arg>`
`-em,--exclude_media_export` => `-exme,--exclude_media_export`
`-oc,--overwrite_csv_export` => `-ow,--overwrite_csv_export`
`-pf,--pem_file </path/to/file.pem>` => `-pem,--pem_file <arg>`
`-id,--form_id <form_id>` => `-f,--form_id <arg>`
`-url,--aggregate_url <url>` => `-s,--aggregate_url <url>`

It also introduces new ones:
`-e,--export                         Export a form`
`-i,--import-odk                     Import from ODK`
`-pa,--pull-aggregate                Pull form from an Aggregate instance`

Since the command line interface exists to allow automations and is generally called through scripts, I think it needs to stay stable. Perhaps these could be changed by a major release but automations that used to work with the previous release should continue working after a minor release.

<strike>@ggalmazor I haven't verified this yet but is it also the case that modifiers (e.g. `--overwrite_csv_export`) now only worked with the newly-introduced task commands (e.g. `-e`)? That would also be a serious breaking change.</strike> I looked at BriefcaseCLI and I believe that is all taken care of.

**Comment by ggalmazor** [comment]
That shouldn’t have happened. I’d swear I reviewed all the cli args and fixed that some weeks ago :( Sorry!

I’ll check that everything works as before

**Comment by lognaturel** [comment]
I think it's just the short codes so hopefully it will be a quick fix!

**Comment by ggalmazor** [comment]
I've created a PR to solve this. The new shortcodes should stay, though, to slowly let our users switch to the new Launcher.
