### ISSUE TITLE
Aggregate Server Connection window needs resizing to read text below login fields.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#312]
#### Software versions 
Briefcase v1.8.x, Java v1.8.x, operating system Windows and Ubuntu.

#### Problem description
Displayed window where you can log in to aggregate account needs resizing if you want to read information below login fields. 

#### Steps to reproduce the problem
1. Go to pull or push section
2. Click on Connect button.
3. Aggregate Server Connection window should display now.

#### Expected behavior
Information below fields should be present in the window all the time without resizing as it is displayed on MacOS.

#### Other information 
Screenshot of problem on Windows, in the left side there is window which appears, and in the right resized one. 
![aggregate connection_win](https://user-images.githubusercontent.com/33342488/35390451-ced29ade-01db-11e8-9260-56d04d4de79d.jpg)

On MacOs information is not cut and looks like that:
<img width="228" alt="aggregate connection" src="https://user-images.githubusercontent.com/33342488/35390530-12fa3e24-01dc-11e8-86d3-0c7c0485a0c6.png">

**Comment by yanokwa** [comment]
@ggalmazor Were you able to repro this problem on Windows 10 or Ubuntu?

**Comment by ggalmazor** [comment]
I didn't try to repro as I knew from the code that the dialog was being sized manually and positioned at the top left corner of the screen.

I thought that we could improve it with what we learned for the conf panel dialog.

**Comment by ggalmazor** [comment]
Also, checked that this dialog shows correctly on linux, mac and win10

**Comment by yanokwa** [comment]
Agreed that this is better! 

But now the two lines of the JLabel looks funny. Is it doable to get them on one line and have them wrap?

**Comment by ggalmazor** [comment]
Ok, fixed the PR with @dcbriccetti's suggestion
