### ISSUE TITLE
Icon fonts not working on windows 10

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#318]
![win_briefcase](https://user-images.githubusercontent.com/205913/35408774-9c5cdc1a-0210-11e8-9230-bae477280e4f.png)

#### Software versions 
Briefcase #bf756a62, Java 1.8.0_161, win10

#### Problem description
No icons shown on the buttons

#### Steps to reproduce the problem
Just run Briefcase and go to the Export tab. Make sure you have pulled some forms before.

#### Expected behavior
![briefcase_icons](https://user-images.githubusercontent.com/205913/35408528-bf33d82a-020f-11e8-8a9f-29ac69d98bdf.png)

#### Other information 
The icons font uses a unicode escape code to show the icon. It could be due to the poor support for unicode on win10

**Comment by yanokwa** [comment]
Hmm. I am not seeing this problem on my Windows 10 machine running Java 1.9.

**Comment by ggalmazor** [comment]
I haven't tried with Java9 and my machine is a virtual machine on VirtualBox running ES locale... Maybe there's a problem with that...

**Comment by yanokwa** [comment]
I've tried Java 8 and Java 9 and I don't see this issue. Could you try the English locale?

**Comment by yanokwa** [comment]
Ugh. The beta build on my Windows machine doesn't show the icons. Can you confirm, @ggalmazor?

**Comment by kkrawczyk123** [comment]
I can confirm that. I have windows 8 and java 1.8.161 and details and other icons are not displayed at all, I just can see an empty buttons.

**Comment by ggalmazor** [comment]
In my Linux box, I can reproduce this problem by manually changing the Swing theme. Not all themes support icons on buttons... 

@dcbriccetti, maybe you know of other possible explanation for this?

**Comment by ggalmazor** [comment]
Ok, I found that on windows the JButtons have an inner lateral padding that's producing this problem. The buttons are simply not wide enough to see the icon.

**Comment by dcbriccetti** [comment]
>@dcbriccetti, maybe you know of other possible explanation for this?

Sorry, no, I don’t.

**Comment by ggalmazor** [comment]
@dcbriccetti don't worry! It's solved :) #332
