### ISSUE TITLE
Input fields are not in the same size on Export section.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#321]
#### Software versions 
Briefcase v1.8.x, Java v1.8.x, operating system: Windows 8.1

#### Problem description
Start Date and End Date fields are longer than Export directory and PEM file location fields.

#### Steps to reproduce the problem
1. Open Export section and look at fields size.

#### Expected behavior
All fields should be unified as they are on MacOS and Ubuntu. 

#### Other information 
Screenshot of situation attached:
![unified fields](https://user-images.githubusercontent.com/33342488/35432735-48368ed0-0281-11e8-9ff3-6b47dd9adb45.jpg)

**Comment by sprea** [comment]
I would like to work on this issue. May I proceed ?

**Comment by ggalmazor** [comment]
Hi @sprea! Sorry, I didn't see your comment...
