### ISSUE TITLE
Set proper date range values for start and end date

### ISSUE THREAD

**Issue by mayank8318** [opendatakit/briefcase#323]
#### Software versions 
Briefcase vv1.8.0-227-gbebd3f5, Java v1.8, Ubuntu, Aggregate v1.x.x, Collect v1.x.x...

#### Problem description
There is no restriction of the date range values in the start date and end date datepickers.

#### Steps to reproduce the problem
Open any datepicker.

#### Expected behavior
The start date should not exceed current date and when a particular start date is selected, the end date values less than the start date should be disabled instead of giving an error message afterwards.

#### Other information 
Set appropriate date range in the DatePickerProperties.

Can I work on this issue?

**Comment by yanokwa** [comment]
Hi @mayank8318! I am unable to reproduce this issue. I am on macOS 10.13 running Java 9, but Java 8 also works great. I've also tried the build you reported and v1.8.0-232-g242dea6.jar. 

Here's the dialog that I see when I choose an end date that's before a start date.
<img width="608" alt="screen shot 2018-01-28 at 20 13 42" src="https://user-images.githubusercontent.com/32369/35493452-328e7ec4-0468-11e8-9fe2-7d8f1f89fa92.png">

**Comment by lognaturel** [comment]
I believe the suggestion here is to disable invalid dates so that the user doesn’t have to wait for the error message to get feedback. 

If that’s indeed the idea, I think it’s a good one worth pursuing.

**Comment by mayank8318** [comment]
@yanokwa What I mean to do is what @lognaturel has said in her comment.  ☺

**Comment by yanokwa** [comment]
@mayank8318 That sounds like a nice feature to add. Please over https://github.com/opendatakit/briefcase/blob/master/CONTRIBUTING.md then claim the issue to start working on it!

**Comment by mayank8318** [comment]
@opendatakit-bot claim
