### ISSUE TITLE
Differences between ui of pull/push and export on all three operating systems

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#330]
#### Software versions 
Briefcase v1.9.Beta, Java v1.8.x, operating system: Ubuntu, Windows and MacOS

#### Problem description
It Beta version is a little difference between pull/push ui and export. 

In pull/push section: When the form is highlighted, whole line should be highlighted. On MacOS is displayed differently then on Ubuntu and Windows, highlight doesn't extend behind details button.
The same differences are present on push section.
Comparison of all three systems: (from left side Ubuntu, MacOs, Windows)
<img width="957" alt="screenshot_briefcase1" src="https://user-images.githubusercontent.com/33342488/35564343-2303e4dc-05ba-11e8-86b4-2a6d0323c06f.png">

In export section are more differences. On Ubuntu highlight doesn't extend behind details button, but it covers export configuration button. On MacOs export configuration button is not highlighted, but details button is covered by highlight shadow. On Windows whole line is highlighted in correct way.
Comparison of all three systems: (from left side Ubuntu, MacOs, Windows)
<img width="931" alt="screenshot_briefcase2" src="https://user-images.githubusercontent.com/33342488/35564551-dce2501e-05ba-11e8-8714-7a4f1c058ea7.png">

#### Expected behavior
All UI's should be unified.

**Comment by ggalmazor** [comment]
I updated the PR solving this issue to note that on a Mac, it will only paint the background when a button is disabled (we don't know why).

We need the buttons to be enabled to allow the users to click them, therefore, there's no apparent way to solve this issue in a way that is consistent across mac, linux and windows.
