### ISSUE TITLE
 Sorting activity in Details column.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#331]
#### Software versions 
Briefcase v1.9.beta, Java v1.8.x, operating system: Ubuntu, MacOs, Windows

#### Problem description
I was just wondering if sorting activity in Details column is needed at all?
There are also differences in behavior according to operating system:
-on Mac and Windows column has a clickable header with arrow but without any sorting activity
-on Ubuntu you can sort items which are present in table but no idea what is the subject of the order.

Issue update:
**Expected behavior of sorting activity of columns headers:**

| Type of column | Text on column | up chevron ▲ | down chevron ▼ |
| --- | --- | --- | --- |
| Selection checkbox col | Empty |selected rows first | selected rows last |
| Details button col | Empty |rows with status history first | rows with status history last |
|Custom conf button bol | Empty |rows with custom conf first | rows with custom conf last |
| Rest of columns | Column name | a-z sorting direction | z-a sorting direction |

**Comment by ggalmazor** [comment]
We could disable sorting on columns with buttons in general. Or if we want to be able to sort, we could define the criteria to "has details" or "has custom conf", etc.

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs discussion"

**Comment by ggalmazor** [comment]
For this issue to be actionable, we should settle on what's expected. I propose the following:
- It must be the same on Mac, Windows, and Linux (that's an easy one to agree upon)
- We disable clicking on headers of columns that don't have text. These are:
  - Selection checkbox column (all three tabs)
  - Details button column (all three tabs)
  - Override configuration button column (only on the export tab)
- We ensure that clicking on the rest of headers sorts the rows using the values on that column
  - up chevron means A-Z sorting direction
  - down chevron means Z-A sorting direction

@yanokwa, @lognaturel, any comments?

**Comment by yanokwa** [comment]
I like your proposal, @ggalmazor, but I do think it's nice to be sort by the columns with icons. For example, if you want to see which forms have custom configurations, a sort would be super useful. 

I think the challenge is fitting header text, but in this case, I don't think header text is a must.

**Comment by ggalmazor** [comment]
I'll try to keep track of the different suggestions...

Summary table:

| Type of column | Text on column | up chevron ▲ | down chevron ▼ |
| --- | --- | --- | --- |
| Selection checkbox col | Empty |selected rows first | selected rows last |
| Details button col | Empty |rows with status history first | rows with status history last |
|Custom conf button bol | Empty |rows with custom conf first | rows with custom conf last |
| Rest of columns | Column name | a-z sorting direction | z-a sorting direction |

**Comment by ggalmazor** [comment]
@kkrawczyk123 Now that we have settled an expected behavior, could you add the table to the original issue description? This way we can tag this one as "contributor friendly"

This is the code for the table:
```markdown
| Type of column | Text on column | up chevron ▲ | down chevron ▼ |
| --- | --- | --- | --- |
| Selection checkbox col | Empty |selected rows first | selected rows last |
| Details button col | Empty |rows with status history first | rows with status history last |
|Custom conf button bol | Empty |rows with custom conf first | rows with custom conf last |
| Rest of columns | Column name | a-z sorting direction | z-a sorting direction |
```

**Comment by jay4kelly** [comment]
@opendatakit-bot claim
