### ISSUE TITLE
Activeness of pull/push button.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#335]
#### Software versions 
Briefcase v1.9.x, probably preview versions too, Java v1.8.x, operating system: All

#### Problem description
I have noticed differences between activeness of pull, push and export button.

#### Steps to reproduce the problem
1.Run briefcase and do not connect to the aggregate server. - Pull button is active, push button is active too.
2. Connect to the aggregate server on pull page - pull button is disabled.
3. Connect to the aggregate server on push page - push button is active.
4. Click on push button, nothing happens.
5. Go back to pull page and you can see that pull button become active. 

#### Expected behavior
I think that pull and push button should act in the same way as an export button which is active only choosing export direction and form from export list. Means they should be active only after connection to the aggregate server and choosing form from the checklist.

#### Other information 
It is not high priority issue but it would be nice to unify all buttons.

**Comment by ggalmazor** [comment]
@opendatakit-bot tag “quick win”

**Comment by ggalmazor** [comment]
@opendatakit-bot tag “quick win”

**Comment by ggalmazor** [comment]
I'd tag this as a quick-win, but @opendatakit-bot doesn't obey :P

**Comment by mayank8318** [comment]
@kkrawczyk123 @ggalmazor Yes this can also lead to Exceptions that we might not be handling and hence the user won't know what happened.

**Comment by mayank8318** [comment]
@opendatakit-bot claim
