### ISSUE TITLE
Settings override button is grayed out without being disabled

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#339]
#### Software versions 
Briefcase v1.9.0 beta

#### Problem description
<img width="43" alt="screen shot 2018-02-04 at 7 34 39 pm" src="https://user-images.githubusercontent.com/967540/35787536-c2b18f3e-09e3-11e8-8512-555943fe7773.png">
This makes it look as though the top button is clickable and the bottom one isn't. In fact it means the top form has a custom configuration and the bottom one doesn't. I don't think this is clear.

#### Steps to reproduce the problem
Go to the export tab.

#### Expected behavior
Graying out should be used to indicate that a control is disabled. I think some other convention should be used to indicate whether or not a custom configuration exists.

**Comment by yanokwa** [comment]
I did this and I agree it is confusing. 

Maybe we should go for a dark green when it is enabled? `008000` is a nice shade that I like.
<img width="96" alt="screen shot 2018-02-04 at 20 37 24" src="https://user-images.githubusercontent.com/32369/35788624-4c75ec2c-09eb-11e8-8975-de11087da937.png">

**Comment by ggalmazor** [comment]
We're talking foreground color, n'est pas?
