### ISSUE TITLE
Compilation warning on CharsetConverterDialog.java

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#355]
This class is overriding a deprecated API and it's triggering a compilation warning: 
```
Note: /home/guillermo/src/odk/briefcase/src/org/opendatakit/briefcase/ui/CharsetConverterDialog.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

#### Software versions 
Briefcase v1.9.0, Java v1.8.0_161, Ubuntu 17.10

#### Problem description
Compilation warnings

#### Steps to reproduce the problem
Running `./gradlew clean compileJava` is enough to trigger the compilation warning.

#### Expected behavior
The project should compile without any compilation warnings.

#### Other information 
Online 397 we find this call which is deprecated:
```java
IOUtils.closeQuietly(bufferedReader);
```
From the Javadoc, we learn that this should be replaced with a [try-with-resources statement](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html)

**Comment by shobhitagarwal1612** [comment]
Can I work on this?

**Comment by yanokwa** [comment]
Sure! Claim away.

**Comment by shobhitagarwal1612** [comment]
@opendatakit-bot claim
