### ISSUE TITLE
Default analytics to “on” and inform users about need

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#357]
We are going to start collecting usage analytics and the PMC would like the analytics to default on and be opt-out. This is in line with our other products (Collect, Build, website, forum, docs, etc).

When there is an opportunity to turn usage reporting off, we can and should give people the option (See http://docs.opendatakit.org/security-privacy/#odk-collect) to turn it off. 

- [x] Change settings to "Gather anonymous usage data to help prioritize fixes and features"
- [x] Default to analytics on
- [x] Improve startup message (https://github.com/opendatakit/briefcase/issues/358)
- [x] File an issue at https://github.com/opendatakit/docs to update the security privacy at http://docs.opendatakit.org/security-privacy

Related #160

**Comment by jpknox** [comment]
Hello, this looks right up my ally; I performed the initial work to integrate Google Analytics into this repo 😃.

I can definitely do the non-GUI stuff but the actual construction and layout of the GUIs will be a blocker for me. I can hook up all the necessary back-end code interactions if a more front-end savvy developer wants to pick up the GUI stuff and work in collaboration with me on this.

**Comment by dcbriccetti** [comment]
Hope you don’t mind the title change. (How do you *on and inform* a user?)

**Comment by yanokwa** [comment]
@jpknox I think you'll find that the first three parts of this issue don't require any UI work. And the last you can do by filing an issue on the docs repo. 

If you are interested in taking this on, reply with `@opendatakit-bot claim`

**Comment by ggalmazor** [comment]
Hi @jpknox! In case you need to change any UI stuff I can help you with that.

**Comment by jpknox** [comment]
Thank you @yanokwa, I'll look into this for ODK. @opendatakit-bot claim
@ggalmazor I'll message you if I run into any Swing :).

**Comment by jpknox** [comment]
Hello, I understand it has been a while but I saw that another user was revamping the way that the analytics works, and he was defaulting it to be "on", I decided to hold fire for some time. Is this ticket still needed?

**Comment by ggalmazor** [comment]
Awesome, @jpknox! Yes, I think this is still needed :)

**Comment by ggalmazor** [comment]
Hi, @jpknox, so you still want to solve this issue?

**Comment by jpknox** [comment]
Sorry I no longer have the time to contribute, at least for this ticket.

**Comment by ggalmazor** [comment]
Hi @jpknox! that's OK, don't worry! I wanted to be sure before suggesting the issue to someone :)

**Comment by ggalmazor** [comment]
Closed, since all the action points have been met

**Comment by ggalmazor** [comment]
Closing, since all the action points have been met
