### ISSUE TITLE
Push / Pull buttons are enabled by default

### ISSUE THREAD

**Issue by shobhitagarwal1612** [opendatakit/briefcase#363]
#### Software versions 
Briefcase v1.9.0

#### Problem description
The `push` and `pull` button in the `Push` and `Pull` tabs are enabled by default (ie when no forms are selected)

#### Expected behavior
They should be disabled

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by mayank8318** [comment]
@shobhitagarwal1612 I am handling this in #337. Please check that PR. :)

**Comment by shobhitagarwal1612** [comment]
Duplicate of #335. Closing
