### ISSUE TITLE
Replace instantiation of abstract classes and interfaces with inlined lambdas

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#369]
Lots of places in Briefcase's code have something similar to this:
```java
EventQueue.invokeLater(new Runnable() {
  public void run() {
    // some code lines here
  }
});
```

We could change all these to:
```java
EventQueue.invokeLater(() -> {
  // some code lines here
});
```

IntelliJ even suggests you do this by using the grey color on the part that could be removed:
![image](https://user-images.githubusercontent.com/205913/36174055-5812305a-110b-11e8-8000-cb23d5daa8fc.png)

Pressing `<alt>+<enter>` on the grey `new Runnable(` text suggests you to "Replace with lambda", which is a safe refactor:
![image](https://user-images.githubusercontent.com/205913/36174141-9b5e713e-110b-11e8-80cd-ac79f753fdda.png)

Some common examples of this are `Runnable` and `ActionListener`

**Comment by ggalmazor** [comment]
@opendatakit-bot label "quick win"

**Comment by emajj** [comment]
@opendatakit-bot claim
