### ISSUE TITLE
Remove explicit type arguments

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#370]
In many places we can find code like this:

```java
List<String> usedAtts = new ArrayList<String>();
```

The type argument on the `ArrayList` can be removed and the line could be:

```java
List<String> usedAtts = new ArrayList<>();
```

Searching in the project with a regular expression "new ArrayList<.+>" would get all the instances of this, but there could be more with `HashMap` or other collection types.

**Comment by ggalmazor** [comment]
@opendatakit-bot label "quick win"

**Comment by emajj** [comment]
@opendatakit-bot claim

**Comment by emajj** [comment]
I cloned the project and navigated to project root and executed

`grep -rn "new ArrayList<.+>" src/`

And that produced no output. Also tried

`grep -rn "new LinkedList<.+>" src/`

`grep -rn "new HashMap<.+> src/`

`grep -rn "new LinkedHashMap<.+> src/`

All produced no output. I had to go through each file one after the other and check for this. Here is my [PR](https://github.com/opendatakit/briefcase/pull/383)
