### ISSUE TITLE
Enable the Indentation module on checkstyle

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#371]
The `Intendation` module is currently disabled, allowing a mix of indentation chars and lengths across the source code on Briefcase.

This module should be enabled by uncommenting its tag on `config/checkstyle/checkstyle.xml` (line 159)

This IntelliJ settings file includes a complying code style scheme: [settings.zip](https://github.com/opendatakit/briefcase/files/1721809/settings.zip) 

You can rename it to `settings.jar` and then import it on IntelliJ with File > Import Settings

**Comment by ggalmazor** [comment]
@opendatakit-bot label "quick win"

**Comment by zjk758** [comment]
Hi, i'd like to take this.

**Comment by zjk758** [comment]
@opendatakit-bot claim

**Comment by KiaFarhang** [comment]
Hi there,

I'd like to claim this issue. Updated the style settings and am currently working through the code base reformatting indentations. Thanks in advance!

@opendatakit-bot claim
