### ISSUE TITLE
Migrate some Listeners to Adapters 

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#372]
Sometimes, we don't really care for all the events a Swing `Listener` object can receive. This is an example on `PullTransferPanel` (line 235):

```java
txtOriginName.addFocusListener(new FocusListener() {
  @Override
  public void focusGained(FocusEvent e) {
    // don't care...
  }

  @Override
  public void focusLost(FocusEvent e) {
    if (txtOriginName.isEditable()) {
      PullTransferPanel.this.updateFormStatuses();
    }
  }
});
```

This `Listener` could be replaced with an `Adapter`, which doesn't force you to implement all its methods:

```java
txtOriginName.addFocusListener(new FocusAdapter() {
  @Override
  public void focusLost(FocusEvent e) {
    if (txtOriginName.isEditable()) {
      PullTransferPanel.this.updateFormStatuses();
    }
  }
});
```

Searching in the project with the regular expression "new \w+Listener\(" will produce a list of places to check for this.

**Comment by ggalmazor** [comment]
@opendatakit-bot label "quick win"

**Comment by gnujavasergio** [comment]
@opendatakit-bot claim

**Comment by gnujavasergio** [comment]
@opendatakit-bot claim

**Comment by mayank8318** [comment]
@ggalmazor Can I work on this as well?

**Comment by ggalmazor** [comment]
Sure!

**Comment by mayank8318** [comment]
@opendatakit-bot claim
