### ISSUE TITLE
Add a way to delete forms from Briefcase Storage

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#373]
This would make testing Briefcase easier (no need to manually delete things and make a mess) and users could also do a little housekeeping of their forms.

Maybe a "delete" button for each form on push and export tabs would be enough.

**Comment by ggalmazor** [comment]
@opendatakit-bot label "enhancement"

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs discussion"

**Comment by mayank8318** [comment]
Do we "delete" delete the forms or move it to a trash folder?

**Comment by grzesiek2010** [comment]
@ggalmazor isn't it the same https://github.com/opendatakit/briefcase/issues/122 ?

**Comment by ggalmazor** [comment]
Closing in favor of @122. Thanks, @grzesiek2010!
