### ISSUE TITLE
CLI unexpected error message should direct users to Slack and help them find log

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#379]
#### Software versions 
Briefcase v1.9.0-88-g42264c07

#### Problem description
Unexpected errors currently result in the following message:
```
Briefcase unexpected error. Please review the logs and contact maintainers on the following URLs:
	https://opendatakit.slack.com/messages/C374LNDK9/
	https://forum.opendatakit.org/c/support
```

#### Steps to reproduce the problem
In this version, specify a date with a format other than yyyy-mm-dd

#### Expected behavior
The message should be something like
```
Briefcase unexpected error. Please review briefcase.log for more information. For help, post to https://forum.opendatakit.org/c/support
```

In general, the forum is a better place for user support. Also, it's important to let the user know where the log is located.

Does the proposed message make sense to others?

**Comment by dsukmanova** [comment]
@opendatakit-bot claim
