### ISSUE TITLE
Provide a human-friendly error message for MissingArgumentException in CLI

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#380]
#### Software versions 
Briefcase v1.9.0-88-g42264c07

#### Problem description
When an argument is missing in CLI mode, the user gets a stack trace.

#### Steps to reproduce the problem
`java -jar build/libs/ODK\ Briefcase\ v1.9.0-88-g42264c07 -pa -id foo -sd ../ -url test -u -p`

#### Expected behavior
The user gets a friendly message about missing values.

**Comment by emajj** [comment]
@opendatakit-bot claim

**Comment by emajj** [comment]
@lognaturel trying to reproduce by executing the command you provided and I got this error

`Error: Unable to access jarfile build/libs/ODK Briefcase v1.9.0-88-g42264c07`

**Comment by ggalmazor** [comment]
HI @emajj! Your jar file will have a different name. Take a look on the file your build produces and fix the command accordingly.

**Comment by emajj** [comment]
I don't have a libs folder inside builds/
Is it that my build was incomplete or? I built from intelij using the instructions on the README

**Comment by ggalmazor** [comment]
Try to launch this: `gradlew clean build -x test`

This launches `clean` and `build` Gradle tasks skipping the tests. You should get the `build/libs` directories and inside that, you should find a JAR file.

**Comment by emajj** [comment]
I get this error when I try to execute that command 

> No command 'gradlew' found, did you mean:
>  Command 'gradle' from package 'gradle' (universe)
> gradlew: command not found

Then I installed gradle using `sudo apt install gradle` 

But I still get that error.

**Comment by ggalmazor** [comment]
Alright :)

You should be able to run `./gradlew clean build -x test` on the project's root directory.

**Comment by emajj** [comment]
so I had to do ./gradlew instead of gradlew

Building. Thanks
