### ISSUE TITLE
NullPointerException when choosing a directory on Pull and Settings tabs

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#385]
https://sentry.io/opendatakit/briefcase/issues/467037766/

```
NullPointerException: None
    at java.io.File.<init>(File.java:277)
    at org.opendatakit.briefcase.ui.WrappedFileChooser.showDialog(WrappedFileChooser.java:106)
    at org.opendatakit.briefcase.ui.PullTransferPanel$OriginActionListener.actionPerformed(PullTransferPanel.java:174)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
...
(34 additional frame(s) were not displayed)
```

**Comment by ggalmazor** [comment]
https://sentry.io/opendatakit/briefcase/issues/467037719/

**Comment by ggalmazor** [comment]
This should be solved by applying `FileChooser` like on the Export tab. 

Examples at:
- `ConfigurationPanelForm.buildPemFileDialog()`
- `ConfigurationPanelForm.buildExportDirDialog()`

**Comment by ggalmazor** [comment]
@opendatakit-bot label "contributor friendly"

**Comment by ggalmazor** [comment]
@opendatakit-bot label "bug"

**Comment by darshan934** [comment]
hi i would like to work on this, can i take this up?

**Comment by ggalmazor** [comment]
Hi @darshan934! This issue required some knowledge of the internals of the export tab code. Have you had a chance to study it before hand?

**Comment by darshan934** [comment]
@ggalmazor I haven't done the required studying. Could you direct me to the reading required? This is the second issue I am working in the ODK briefcase as part of Outreachy. 
Or would you recommend me taking another issue?

**Comment by ggalmazor** [comment]
Hi @darshan934! If that's the case, I'd recommend doing two or three more "quick wins" to get to know the base code a little bit more.

I think any of these could work:
- https://github.com/opendatakit/briefcase/issues/372
- https://github.com/opendatakit/briefcase/issues/379
- https://github.com/opendatakit/briefcase/issues/213

**Comment by darshan934** [comment]
Okay thank you so much!

**Comment by emajj** [comment]
@opendatakit-bot claim

**Comment by emajj** [comment]
@opendatakit-bot unclaim

**Comment by emajj** [comment]
I was not able to reproduce this

**Comment by ggalmazor** [comment]
I'll give it a go and close if I get the same results. Thanks, @emajj!

**Comment by ggalmazor** [comment]
Closing, since the `FileChooser` has been applied to all tabs already.
