### ISSUE TITLE
Remove Eclipse specific files

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#39]
IntelliJ and gradle are the chosen development tools so `.classpath` and `.project` should be removed.  The jars for all libraries that are now managed by gradle should also be removed.

`forms-1.3.0.jar` and `forms-1.3.0-src.zip` are files that are added by Eclipse's UI building tool (Windows Builder). I don't think they are used and so they should be removed.

**Comment by yanokwa** [comment]
@mitchellsundt Do you use Eclipse for your Briefcase work? If we remove these files and go to a gradle setup, will it break your build?

**Comment by mitchellsundt** [comment]
I use eclipse, but if you migrate to gradle, that's fine. I can switch to Intellij. Feel free to do this with the other tools (e.g., Validate, javarosa). We should probably talk before you tackle Aggregate, though, as the entire project would need to be restructured.
