### ISSUE TITLE
Remove ./gradlew lint from the contributing guide

### ISSUE THREAD

**Issue by emajj** [opendatakit/briefcase#390]
#### Problem description
`./gradlew lint` from the contributing guide gives error

> Task 'lint' not found in root project 'briefcase'. Some candidates are: 'init'.

#### Steps to reproduce the problem
run `./gradlew lint` from briefcase root

#### Other information 
We don't use a linter in Briefcase. The only task that currently should ve run to verify that some changes are ready to be committed is `./gradlew check`.

**Comment by ggalmazor** [comment]
Thanks for creating this issue!

As "Expected behavior" I'd take a look what that task does in other ODK projects such as ODK Collect and specify it.
