### ISSUE TITLE
Investigate why Briefcase generates so many tempfiles

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#399]
#### Software versions 
Briefcase v1.9.0

#### Problem description
In my Briefcase storage directory, I have thousands of files like this.
```
tempDefn3877521673688654.xml
tempDefn6383827758320310.xml
tempDefn7142323728157348.xml
```
They aren't used for anything that I can see and they are never removed.

#### Steps to reproduce the problem
Not sure. That's part of the fun of this issue :)

#### Expected behavior
Temp files are created in the OSes temp directory and are thrown away when not needed. 

#### Other information 
I generally use the CLI on cron and not the GUI.

**Comment by yanokwa** [comment]
@opendatakit-bot claim

**Comment by yanokwa** [comment]
@opendatakit-bot unclaim

**Comment by ggalmazor** [comment]
At least we could ensure temp files and folders are created in the corresponding temp folder according to each particular OS. Each OS has its way of deleting those according to some schedule or when they reboot.

Another improvement could be to track every temp file and folder created by Briefcase and trying to delete them on exit but that would require changes across the whole app. They way to go about it would be:
- First, refactor all the places where we require temp files/folders to depend on a unique supplier
- Then, change the supplier to track every supplied `Path` and add an exit hook to make a "best effort" to delete them.

**Comment by ggalmazor** [comment]
> In my Briefcase storage directory, I have thousands of files like this.
> 
>    tempDefn3877521673688654.xml
>    tempDefn6383827758320310.xml
>    tempDefn7142323728157348.xml

@yanokwa, I think tihs doesn't happen with the current master anyway. Could you remove those and see if more pop up?

**Comment by lognaturel** [comment]
Confirmed that these don't get created anymore.
