### ISSUE TITLE
Don't log usage issues to Sentry, especially if they include user info

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#401]
Currently, some error text logged to Sentry includes user info such as full paths on their machines or form elements.

For example:
- lines 428 and 431 of `FileSystemUtils`
- lines 136 and 138 of `AggregateUtils`

These logged items don't correspond to problems with Briefcase but rather with current state (missing file, server down, etc). Ideally this information makes it back to the user through the primary UI (GUI or CLI). The personal info should never be sent to Sentry.

Those specific examples could be logged at info level, I think.

**Comment by ggalmazor** [comment]
OK:
- I'll raise to `INFO` level or create new log lines with any sensitive information that could be useful while debugging
- I'll remove all sensitive information from `WARN` level messages

**Comment by ggalmazor** [comment]
I'm already seeing the need for separating actionable errors (by us) from errors related to forms and submissions, which we won't be able to do much about. Sentry should receive only actionable events...

This could be implemented either through [MDC](https://logback.qos.ch/manual/mdc.html) or direct use of Sentry's API but I think we will probably have to create a logging/reporting abstraction on top of that.
