### ISSUE TITLE
Provide feedback when export is ongoing

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#402]
Prior to multiple exports being added, it was obvious that an export was ongoing because the export button would be disabled and the status button was clickable. Now there is no feedback that an export is ongoing.

A simple approach would be to add "Exporting..." to the right of the `Select All` button with dots added each time an event is fired. If all exports complete, remove the text. There's some chance that completion won't be detected because the event bus is not reliable but because it's just text and not enabled/disabled buttons it's not a very big deal.

@ggalmazor interested in knowing what you think is possible here.

**Comment by ggalmazor** [comment]
Yes, we could try that while we make improvements to the bulk exporting that would let us know exactly when an export is started and finished.

To protect us against EventBus quirks, we could start a countdown of, say, 5 seconds, to hide the message if no new event has been received.

**Comment by Thodoris1999** [comment]
@opendatakit-bot claim
