### ISSUE TITLE
Add pull before export option to CLI operation

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#408]
We have this option on the UI and we should bring that into the CLI as well. 

This would simplify any automatization scripts by removing the need of executing Briefcase for pulling the forms before exporting them.

Pulling from an Aggregate server requires hard-coding passwords on the CLI command. By removing those operations from such scripts we can make them more secure as well.

In order to benefit from this new option, users would make sure that:

1. They have selected the option to "Remember passwords" on the settings tab
2. After this, they have pulled at least once every form which they'd want to export on the CLI

The proposed CLI param would be `-pb` and `--pull_before`.

**Comment by neoliteconsultant** [comment]
@opendatakit-bot claim

**Comment by neoliteconsultant** [comment]
I am still working on it

**Comment by neoliteconsultant** [comment]
l have already submitted a pull request
