### ISSUE TITLE
UX clean up for overwrite existing files feature

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#409]
- [ ] Remove icon on confirmation dialog https://github.com/opendatakit/briefcase/pull/404#issuecomment-371435677
- [ ] ~~Add title to confirmation dialog https://github.com/opendatakit/briefcase/pull/404#issuecomment-371511483~~
- [ ] Add vertical spacer https://github.com/opendatakit/briefcase/pull/404#issuecomment-371450318

**Comment by emajj** [comment]
Thanks @yanokwa and I'll get right on this. @kkrawczyk123 I noticed the absence of the title but was not just sure what to use as the title as I couldn't think of anything else other than "Overwrite existing files". I felt having that as a title and a body message again was redundant.

**Comment by yanokwa** [comment]
@emajj I talked with @lognaturel and she suggested we leave the title off. I agree!

**Comment by emajj** [comment]
@ggalmazor this is still open. I thought my PR was already approved :smile:
