### ISSUE TITLE
Provide an option to disable exporting media files on the UI

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#413]
The CLI export operation supports disabling the export of media file attachments to submissions.

We should add a new export configuration option to disable on the UI as well.

**Comment by ggalmazor** [comment]
Hi @ravi808! You can check PRs #404, and #411, which solve a similar issue about another option on the same tab.

You will have to modify the following files:
- Using IntelliJ's UI Designer: `ConfigurationPanelForm.form` to add a new checkbox and other UI elements
- `ConfigurationPanelForm.java` to create appropriate callbacks and methods that would be used by the `ConfigurationPanel` component
- `ExportConfiguration` class, to add a new configuration setting.
- `ExportAction.export` to hook the new setting on the export operation.

Both PRs have extensive conversations between @emajj (the author) and me. You can read them and ask anything you need here :)

**Comment by ravi808** [comment]
Thank you @ggalmazor

**Comment by emajj** [comment]
@ravi808 if you are working on this can you claim it following the instructions here https://github.com/opendatakit/briefcase/blob/master/CONTRIBUTING.md#submitting-a-pull-request

If not then I'd like to work on this :slightly_smiling_face:

**Comment by ggalmazor** [comment]
Hi, @ravi808!

I wanted to check on you about this issue's progress. 

We need to make more changes to the `ExportConfiguration` object and this issue could be blocking us in the near future. If you think you won't be able to work on it, it's totally OK and we can take it from you. If not, please, tell us when you expect to have a PR ready :)
