### ISSUE TITLE
Confirm that form push always uploads the blank form and its media

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#420]
I believe if you attempt a push to Aggregate, Briefcase uploads the form definition and its media to the server each time. If you have a large form, this is a waste of time and precious bandwidth.

1. Confirm that blank forms do get uploaded each time.
1. If the above is true, file an issue to prevent this behavior

**Comment by ggalmazor** [comment]
OK, confirmed that all blank forms are uploaded before sending submissions. Check out this line https://github.com/opendatakit/briefcase/blob/master/src/org/opendatakit/briefcase/util/ServerUploader.java#L207
