### ISSUE TITLE
Use progress bars where appropriate

### ISSUE THREAD

**Issue by dcbriccetti** [opendatakit/briefcase#421]
Instead of, for example, 

Exporting........

Have a progress bar. Where we can’t predict when the task will complete, make it indeterminate:

https://docs.oracle.com/javase/8/docs/api/javax/swing/JProgressBar.html#setIndeterminate-boolean-

**Comment by ggalmazor** [comment]
This would be great. I think we're using that kind of feedback on the pull, push and export tabs.

**Comment by emajj** [comment]
Let me give this a shot :slightly_smiling_face:

**Comment by emajj** [comment]
@opendatakit-bot claim
