### ISSUE TITLE
Allow non-integer strings in the form definition version field 

### ISSUE THREAD

**Issue by tinok** [opendatakit/briefcase#423]
#### Software versions 
Briefcase v1.9.0

#### Problem description
Briefcase fails to validate the form definition, even though the form is valid (created through pyxform, validated through ODK Validate). Once we know what the issue is we can fix it on the [KoBo](https://github.com/kobotoolbox/kpi) side, but maybe this is also a bug on the Briefcase side given the error message.

```
Fetching form definition
resolving against briefcase form definitions
Error parsing form definition: org.opendatakit.aggregate.exception.ODKIncompleteSubmissionData: The data model does not have an id or xmlns attribute.  Add an id="your.domain.org:formId" attribute to the top-level instance data element of your form.
```

#### Steps to reproduce the problem
1. Create any form with kobo.humanitarianresponse.info, deploy
1. Set Briefcase with the correct credentials and hit Pull

#### Expected behavior
Form definition is parsed successfully OR error message displays relevant information 

#### Other information 
This applies to any form generated through KoBo's `kpi` tool; whereas forms created through KoBo's legacy `kobocat` tool succeed with Briefcase. 

Here are the XML files that [don't work](https://0bin.net/paste/bnxbtqchxjkUOU4O#veNWV211FExy2nvX7xwxQ0hTJfErDf7cxxKXIoAHIwC) (kpi-generated) and [do work](https://0bin.net/paste/fuoXYCT2PkH-gfSF#1tDxaOdQkAWSiZArcWRy1fTfaA+ZWzBzPXWdow0RAv+) (kobocat generated). The only minor difference is the name of the XML data model/formID. 

[Related code section in the parser](https://github.com/opendatakit/briefcase/blob/57eea1d7782da7ad77794530d503f182e02f6ad8/src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java#L560-L563)

**Comment by tinok** [comment]
Update: It seems that forms fail to parse because the version is a string of letters rather than the expected integer (which should ideally be a timestamp according to [the parser](https://github.com/opendatakit/briefcase/blob/57eea1d7782da7ad77794530d503f182e02f6ad8/src/org/opendatakit/aggregate/parser/BaseFormParserForJavaRosa.java#L752-L778)).

A better error message could say 'the version string is not a valid integer'.

**Comment by tinok** [comment]
Another potential solution would be to allow the parser to process single forms with a version string (rather than an integer/timestamp) and only throw an error if multiple form versions have been downloaded from multiple `Pull` actions. This would allow users to pull / push their data even with current forms that have a text string as the version.

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs discussion"

**Comment by ggalmazor** [comment]
Hi @tinok, thanks for filing this issue!

Thanks for adding instructions to create a form that would produce the error but it would be much simpler if you attached to the issue a form file directly. You just need to change its extension to `.txt` to let GitHub attach it. 

That way, it's easier for anyone to try to reproduce the issue and work on a solution.

**Comment by douihechmaha** [comment]
hi, Yes @ggalmazor i do agree with you.because it is not clear how to reproduce the issue

**Comment by lognaturel** [comment]
Thanks for the report, @tinok. I do think the original issue was clear but to make it even easier, the form to work with is 
[kpi.xml.txt](https://github.com/opendatakit/briefcase/files/1849623/kpi.xml.txt). 

Arbitrary version strings should be allowed by Briefcase. I don't see any reason for the limitation other than that the parser code was copied from Aggregate. Briefcase should not need to care about versions at all, I believe.

**Comment by tinok** [comment]
Thanks for clarifying @lognaturel, much appreciated! It would be great if a future version of Briefcase could allow arbitrary version strings. It would definitely help a few KoBo users who can't use the tool anymore since we began using non-numeric version strings.

Not sure how big of an effort it is to change this but let's chat offline if it's hard to prioritize this right now.

**Comment by ggalmazor** [comment]
Hi @tinok! I've just created PR #427 to solve this issue. I haven't been able to test this with a Kobo instance, though. If there is any way for me to use any running instance of Kobo, I could do some extra checks to ensure everything works.

**Comment by tinok** [comment]
Amazing, @ggalmazor I'll send you credentials with which you can test this.

**Comment by ggalmazor** [comment]
Thanks, @tinok!
