### ISSUE TITLE
Verify Briefcase runs on Java 10

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#426]
If it doesn't run, describe how it fails, and fix it. Be sure to verify encrypted exports.

**Comment by ggalmazor** [comment]
My test results with a Debian 9 Buster, Java 10.0.0-oracle
- It runs successfully
- Exports encrypted forms

**Comment by yanokwa** [comment]
@kkrawczyk123 Can you please add a test case to confirm Briefcase releases can export encrypted forms on Java 8, 9, 10 on Windows, macOS, and Ubuntu?

**Comment by kkrawczyk123** [comment]
@yanokwa sure, I will!
