### ISSUE TITLE
Remove versionString member in favor of modelVersion in XFormParameters

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#433]
As a result of the work in PR https://github.com/opendatakit/briefcase/pull/427#issuecomment-378353494, the `XFormParameters` has the same value duplicated on its `versionString` and `modelVersion` members.

We should replace every use of `versionString` with `modelVersion` and remove the member once no one depends on it.

**Comment by ggalmazor** [comment]
@opendatakit-bot label "quick-win"

**Comment by ggalmazor** [comment]
@opendatakit-bot label "quick win"

**Comment by CicadasOutsideMyWindow** [comment]
@opendatakit-bot claim
