### ISSUE TITLE
List all operations in CLI help

### ISSUE THREAD

**Issue by xNeophyte** [opendatakit/briefcase#450]
#### Software versions 
Briefcase v1.10.0

#### Problem description
The command line help provides a list of general arguments but does not list the operations in which those arguments can be used. The only way I know of to view the listing of available CLI operations and their arguments is to attempt to call an already known CLI operation with missing parameters. 

#### Steps to reproduce the problem

1. Use the following command at CLI: `java -jar ODK-Briefcase-v1.10.0-beta.0.jar help`
2. Use the following command at CLI: `java -jar ODK-Briefcase-v1.10.0-beta.0.jar -psha`

#### Expected behavior

Using the following command at CLI: `java -jar ODK-Briefcase-v1.10.0-beta.0.jar help` should display information about the list of operations available at the command line.

#### Other information 

`java -jar ODK-Briefcase-v1.10.0-beta.0.jar help`
![image](https://user-images.githubusercontent.com/27878539/38585018-f9404e46-3cdd-11e8-8389-ebc461bd1e87.png)

`java -jar ODK-Briefcase-v1.10.0-beta.0.jar -psha`
![image](https://user-images.githubusercontent.com/27878539/38585078-2c555ea2-3cde-11e8-8e20-7e8e101391d4.png)

**Comment by ggalmazor** [comment]
Hi, @xNeophyte! Thanks for reporting this issue. You are seeing is the “old” legacy help message.

To get the new help message, which shows the operarion list and their arguments in a more detailed fashion, you can execute Briefcase with the `-h` flag.

We are working to make the cli interface more coherent and user friendly. #442 will help us to unify the help message on the legacy mode and show some useful warning messages.

**Comment by yanokwa** [comment]
Closed by #441
