### ISSUE TITLE
Explain users that the export date range is inclusive

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#456]
#### Software versions 
Briefcase v1.10.1

#### Problem description
As discussed in #159, the export date range start and end dates are inclusive both in the GUI and the CLI. We should explicitly tell the users about this.

#### Steps to reproduce the problem
N/A

#### Expected behavior
This is what I propose as a narrow solution:
- The labels of the date range fields on the GUI should read "(inclusive)"
- The CLI help messages of the date start and end params should read "(inclusive)"

#### Other information 
N/A

**Comment by neoliteconsultant** [comment]
@opendatakit-bot claim

**Comment by neoliteconsultant** [comment]
@opendatakit-bot claim --force
