### ISSUE TITLE
Align vertically the progress bars

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#460]
#### Software versions 
Briefcase v1.10.1, All OSes

#### Problem description
After #434, we replaced a text with a progress bar, which is slightly unaligned in the vertical axis respect to other elements at the bottom of the UI. This happens on the Pull, Push and Export tabs.

#### Steps to reproduce the problem
Pull, push and export some forms to see the progress bar.

#### Expected behavior
The progress bar should always be vertically aligned respect to other elements on the bottom of the UI.

#### Other information 
The Push and Pull tabs haven't been migrated to the new `.form` files using IntelliJ's UI Designer, which will require some manual layout juggling.

The fix for the Export tab should be done using IntelliJ's UI Designer.

**Comment by neoliteconsultant** [comment]
@opendatakit-bot claim

**Comment by ggalmazor** [comment]
Hi @neoliteconsultant, thanks for your interest on solving this one :)

The thing is that I'm solving this one indirectly in #463 

Could you take another one please?

**Comment by ggalmazor** [comment]
@opendatakit-bot claim

**Comment by ggalmazor** [comment]
This issue has been solved by #466

We can close this one :)
