### ISSUE TITLE
First column which includes checkboxes of pull table is grayed out in the middle of pull process on ubuntu.  

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#476]
#### Software versions 
Briefcase v1.10.x, Java v1.8.x, operating system: Ubuntu

#### Problem description
The first column which includes checkboxes of pull table is grayed out in the middle of pull process on Ubuntu.  Screenshot attached:
![screenshot from 2018-05-28 16-17-09](https://user-images.githubusercontent.com/33342488/40618709-a90e70e4-6292-11e8-9565-e4c5910385fa.png)

#### Steps to reproduce the problem
1. Run briefcase on ubuntu
2. Connect to server
3. Pull some forms

#### Expected behavior
None columns were grayed out before and none of them are on MacOs and Windows.

**Comment by ggalmazor** [comment]
This is expected. It's grayed out because it becomes disabled to prevent user interaction with the UI while it's doing the pulling/pushing.

It's an improvement introduced with this PR.

**Comment by ggalmazor** [comment]
@yanokwa, @lognaturel, I think we can close this one.
