### ISSUE TITLE
Scroll overlaps details buttons on the export view on Ubuntu and Windows.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#478]
#### Software versions 
Briefcase v1.10.x, Java v1.8.x, operating system: Ubuntu, Windows

#### Problem description
Scroll overlaps details buttons on the export view.
Screenshot attached:
![exportwin](https://user-images.githubusercontent.com/33342488/40656757-b30777e0-6345-11e8-9439-db861add65a4.png)
![export](https://user-images.githubusercontent.com/33342488/40656758-b324953c-6345-11e8-8521-54d18e918679.png)

#### Steps to reproduce the problem
1. Run briefcase newest master
2. Go to Export tab.

#### Expected behavior
Scroll shouldn't overlap details button. Export list should fit to the window as on Pull and Push tabs.

**Comment by ggalmazor** [comment]
This should be solved in #474

**Comment by ggalmazor** [comment]
This issue has been solved in #474. Maybe we close it?

**Comment by kkrawczyk123** [comment]
I confirm that issue doesn't occur anymore on the newest master, tested on all three systems.

**Comment by ggalmazor** [comment]
Another one that we can close :)

**Comment by lognaturel** [comment]
@kkrawczyk123 if it's an issue that you've created you can go ahead and close it as soon as it's resolved. 😊
