### ISSUE TITLE
During first briefcase run push and export list shouldn't depend on pull.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#479]
#### Software versions 
Briefcase v1.10.x, Java v1.8.x, operating system: Ubuntu, MacOS and Windows.

#### Problem description
User used briefcase before and his storage directory is full of forms. User runs new briefcase version. Server url is even saved and pull list is visible. Aggregate url on push tab is saved too but push list is empty and export list also - but they should depend on storage directory content and be loaded automatically as it used to be before. I think that user should be able to use pull, push and export functionalities separately and independently too. As there is no option to refresh all list I go to pull and pull and least one form. Then finally push and export lists are loaded. 
Push and export lists were restored when I run, close, run close and run and close briefcase every time I tried - but pull list wasn't restored all the time on Ubuntu so I had to click on reset button even if url was visible on pull tab I had to input connection credentials again and again. 

What do you think about use case like that @yanokwa @lognaturel @ggalmazor

**Comment by ggalmazor** [comment]
There's a trick the users can do to work around this: reset the storage directory and set it again. That restarts the form cache.

Maybe we could add a button for doing that on the settings tab: "Restart cache"

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs discussion"

**Comment by ggalmazor** [comment]
This is a mockup of the new proposed button:
![image](https://user-images.githubusercontent.com/205913/40765466-d161c26e-64ac-11e8-9ba4-8a840811f5f1.png)

It would appear only when the storage location has been set.

**Comment by lognaturel** [comment]
> but they should depend on storage directory content and be loaded automatically as it used to be before.

I missed when and why this change was introduced. Is it an unintentional side-effect of some of the other refactors? I agree with @kkrawczyk123 that this new behavior is very surprising, especially coming from earlier versions! It would be ideal if we could go back to the prior behavior.

> There's a trick the users can do to work around this: reset the storage directory and set it again. That restarts the form cache.

I wasn't able to get this to work. I downloaded several forms on master from a week or so ago and could see them in export. Then I updated to the latest master and they all disappeared. I reset the storage directory and set it again, I still couldn't see anything in export. I reset the storage directory, closed Briefcase, deleted the cache file, reopened Briefcase and still couldn't see any of the forms from my storage directory. I downgraded to v1.10.0 and confirmed that they are visible.

The forms cache button is ok for resetting after a manual change to the directory or something like that but it really feels like load should be automatic on Briefcase's launch.

**Comment by ggalmazor** [comment]
> The forms cache button is ok for resetting after a manual change to the directory or something like that but it really feels like load should be automatic on Briefcase's launch.

You're both totally correct. I'll review this to make the launch of the new version seamless.
