### ISSUE TITLE
Pull Data from Custom Directory configuration.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#480]
#### Software versions 
Briefcase v1.10.x, Java v1.8.x, operating system Ubuntu and Windows

#### Problem description
When choosing Custom Directory to pull data from configuration in choosing window there is the default filter "ODK Collect Folders" but it is not the most comfortable solution as you cannot go through directories to actually look for odk directory and it is better to change the filter for All files to see all folders in displayed window. Screenshot attached:
![compare](https://user-images.githubusercontent.com/33342488/40663848-e9ed7a70-6359-11e8-9623-c272c49c7661.png)

There is another option to pull data from now it is "Individual form in the computer" and when configuring, there is a filter "XML file" is selected as default but it actually enables a user to go through directories, as on attached screenshot:
![odkform](https://user-images.githubusercontent.com/33342488/40664103-78815540-635a-11e8-8475-8f7d5d9413a2.png)
And this solution is more user-friendly. I would suggest something like that in the first case of just changing the default filter to All files or Directories as it used to be before ui changes.

**Comment by ggalmazor** [comment]
Thanks, @kkrawczyk123!

**Comment by ggalmazor** [comment]
@kkrawczyk123, I've solved this issue through the open PR #474

**Comment by ggalmazor** [comment]
This issue has been solved in #474. Maybe we close it?

**Comment by kkrawczyk123** [comment]
This issue has been fixed on the newest master, tested on all 3 systems.
