### ISSUE TITLE
Ensure date range behaves as discussed in #477

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#486]
Following up on the discussion starting at https://github.com/opendatakit/briefcase/pull/477#issuecomment-394273006

> When I specify a start and end date, I expect that if the textual representation of that date is in the submission XML, it will be included in the output.

**Comment by ggalmazor** [comment]
This has been solved by https://github.com/opendatakit/briefcase/pull/474/commits/cbeacc3070eb09584823ce50602538e9da790dca

**Comment by kkrawczyk123** [comment]
I confirm that is works on the newest master, tested on all three systems.

**Comment by lognaturel** [comment]
Nice! This makes a lot more sense. 🙏 🎉
