### ISSUE TITLE
Pulling can be triggered multiple times for the same form leading to ConcurrentModificationException

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#49]
#### Software versions 
Briefcase v1.4.9

#### Problem description
Pulling can be triggered multiple times for the same form. This can sometimes result in a `ConcurrentModificationException` if the same instance happens to be downloaded at the same time. Plus, it's inefficient.

#### Steps to reproduce the problem
1. Select a form
1. Click on the pull button
1. Unselect the form and then reselect it, this makes the pull button active again
1. Click on the pull button, the form will be pulled a second time.

#### Expected behavior
The pull button should always be inactive when only forms that are currently being pulled are selected.

#### Other information 
I believe I first triggered this by starting a pull on one form, realizing I also wanted to pull a second one, and selecting that second one without unchecking the first. This is probably a more likely scenario. 

The easiest fix might be to make it impossible to select a form that is currently downloading.

**Comment by rclakmal** [comment]
@lognaturel  I am looking into this :)

**Comment by rclakmal** [comment]
@lognaturel Created a PR. Have a look when you get time :)
