### ISSUE TITLE
Form list is empty on Pull tab when the user restarts Briefcase

### ISSUE THREAD

**Issue by mmarciniak90** [opendatakit/briefcase#491]
#### Software versions 
Briefcase master
Java v1.8
operating system: Linux, Windows
Problem is not visible on macOS

#### Problem description
EDIT: Problem is visible only when credentials are required.
Form list is empty on Pull tab when the user restarts Briefcase
The empty list was also on v1.10.1 but the user was not connected to Aggregate. 
![2](https://user-images.githubusercontent.com/3907554/41043079-a35c9836-6992-11e8-83c7-2deaeeef086b.png)
Now, the user needs to reset and add URL and credentials again. 
#### Steps to reproduce the problem
1. The user opens Briefcase and connects to Aggregate
2. The user sees forms on the Pull tab
![1](https://user-images.githubusercontent.com/3907554/41034361-d79d1dc4-6978-11e8-9536-f8711bd7adb3.png)
3. The user closes Briefcase
4. The user reopens Briefcase
5. The user is connected to aggregate but form list is empty
![2](https://user-images.githubusercontent.com/3907554/41034366-db7b50e6-6978-11e8-9b38-0634a06ba4ee.png)

#### Expected behavior
Forms are visible

**Comment by ggalmazor** [comment]
I can't reproduce. Could it have to do with the networking issues you've had today? 

Could you activate logs and see if there is any error trace in it?

I'm using my server https://gigiaggregate.appspot.com, which doesn't require any credentials to pull forms.

**Comment by ggalmazor** [comment]
![issue_491](https://user-images.githubusercontent.com/205913/41044376-6a2aa8aa-69a6-11e8-9f35-d5ce1c02b878.gif)

**Comment by mmarciniak90** [comment]
@ggalmazor, you have right, this problem is not visible in your instance because it doesn't require any credentials.
Problem is visible only when credentials are required.

**Comment by ggalmazor** [comment]
Also can't reproduce. I have removed all permissions from the anon user in my Aggregate server to be sure that the only way to get the form list is by using correct credentials and it works as expected between launches of Briefcase.

I'm suspecting that it would fail when the "remember passwords" setting is not checked, though. I'll explore that scenario.

**Comment by mmarciniak90** [comment]
Agree, `Remember passwords` is a condition of this problem. 
I feel that it is not user-friendly. I was confused. 
Not only me, it was also reported on forum https://forum.opendatakit.org/t/odk-briefcase-v1-11-beta/13432

I see two ways to resolve this problem:
1. Remember passwords is selected as a default which is not the best practice.
2. User sees ![1](https://user-images.githubusercontent.com/3907554/41096624-bdf6939c-6a44-11e8-9b62-76e01b322b24.png) instead of 
![2](https://user-images.githubusercontent.com/3907554/41096630-c1fed95e-6a44-11e8-807c-f481aa64ceba.png) when the user restarts Briefcase when `Remember passwords` was not selected

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "needs discussion"

**Comment by yanokwa** [comment]
I think @ggalmazor's quick workaround is pretty reasonable.

**Comment by ggalmazor** [comment]
> Since we're in the middle of a release, I'd just remove the URL as well when the "remember passwords" is not checked. This would get an empty source when launching Briefcase again, avoiding the problem for the moment and giving us more time to work on a more involved fix.

I'll prepare a PR with this during my morning.
