### ISSUE TITLE
Only export process is tracked on Google Analytics.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#493]
#### Software versions 
Briefcase v1.10.x, Java v1.x.x, operating system: all

#### Problem description
Pull and push processes are not visible on Google Analytics.

#### Steps to reproduce the problem
Pull/push some forms and track real-time actions on Google Analytics.

#### Expected behavior
All processes pull/push/export should be tracked 

#### Other information 
Export is tracked properly.

**Comment by dcbriccetti** [comment]
It seems we’re getting very thorough testing here. Nice work, @kkrawczyk123!
