### ISSUE TITLE
The user needs to click two times to unselect `Use HPPT Proxy` if he manipulates the Port value

### ISSUE THREAD

**Issue by mmarciniak90** [opendatakit/briefcase#509]
#### Software versions 
Briefcase v1.11
operating system: Ubuntu, macOS, Windows

#### Problem description
The user needs to click two times to unselect `Use HPPT Proxy` if he manipulates the Port value

#### Steps to reproduce the problem
1. The user selects checkbox `Use HTTP Proxy`
2. The user changes `Port` value
3. The user clicks to unselect the checkbox `Use HTTP Proxy`
4. The checkbox is not unselected. `Port` value is changed to default 8080.

#### Expected behavior
The checkbox is unselected when the user clicks on it. `Port` value is changed to default 8080 at the same time. It should work just like the Host.

**Comment by ggalmazor** [comment]
@opendatakit-bot claim
