### ISSUE TITLE
Form lists on Push and Export do not contain forms which were pulled with success if user cancels pull

### ISSUE THREAD

**Issue by mmarciniak90** [opendatakit/briefcase#510]
#### Software versions 
Briefcase v1.11.0
operating system: Linux, macOS, Windows

#### Problem description
* Form list on `Export` does not contain forms which were pulled with success if user cancels pull
* Form list on `Push` does not contain forms which were pulled with success if user cancels pull

#### Steps to reproduce the problem
1. User opens Briefcase as the first time
2. User adds Storage directory
3. User connects to Aggregate on Pull tab
4. List of forms is visible (Push and Export list of forms is empty)
5. User selects few forms or clicks on Select all
6. User cancels when few forms are pulled with success
![1](https://user-images.githubusercontent.com/3907554/41087516-7475d89e-6a2c-11e8-9f69-ff7e0fc6953a.png)
7. List form on `Export` is empty
![2](https://user-images.githubusercontent.com/3907554/41087549-884e7880-6a2c-11e8-8674-dd95d683f0d2.png)
7. List form on `Push` is empty

Use case 2 - continuation:
1. User restart Briefcase
2. User goes to `Export` tab
3. Form list on `Export` is empty
4. User goes to `Push` tab
5. Form list on `Push` is empty

Use case 3 - continuation
1. User pull one form and does not cancel
2. All previous forms are visible on form list on `Export` tab
3. All previous forms are visible on form list on `Push` tab

#### Expected behavior
* Form list on `Export` always contains forms which were pulled with success
* Form list on `Push` always contains forms which were pulled with success

**Comment by ggalmazor** [comment]
@opendatakit-bot claim
