### ISSUE TITLE
CSV file has not a doubled content when `Overwrite existing files` is not selected

### ISSUE THREAD

**Issue by mmarciniak90** [opendatakit/briefcase#511]
#### Software versions 
Briefcase v1.11.0, 
operating system: Linux, macOS, Windows
**Regression**

#### Problem description
CSV file has not a doubled content when `Overwrite existing files` is not selected

#### Steps to reproduce the problem
1. The user opens Briefcase as the first time
2. The user adds Storage directory
3. The user connects to Aggregate on `Pull` tab
4. The user selects form and pulls
5. The user goes to `Export` tab
6. The user selects form and exports
7. The user exports the same form without choosing the overwrite checkbox.

#### Expected behavior
CSV file has a doubled content.

#### Workaround
1. The user selects `Overwrite existing files`
2. The user unselects `Overwrite existing files`
3. CSV file has a doubled content.

**Comment by ggalmazor** [comment]
@opendatakit-bot claim
