### ISSUE TITLE
Log file not created

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#522]
#### Software versions 
Briefcase v1.1.11.beta

#### Problem description
@aurdipas did not have a log file after running the beta: https://forum.opendatakit.org/t/odk-briefcase-v1-11-beta/13432/13

#### Steps to reproduce the problem
Java version "1.8.0_172"
Windows 7 enterprise Service pack 1

#### Expected behavior
A log file should be created.

**Comment by ggalmazor** [comment]
This has to do with the build process: a configured `logback.xml` has to be placed in the `res` directory.

That logback conf file has to have a file appender configured to produce a `briefcase.log` file.

**Comment by ggalmazor** [comment]
For a long time, I have been wanting to add a `.example` file with that. @kkrawczyk123 would benefit from that too for the QA tests.

**Comment by ggalmazor** [comment]
I think this one can be closed :)

**Comment by lognaturel** [comment]
👍Do you remember why you said "partially addresses" in #526?

**Comment by ggalmazor** [comment]
Sure! I wanted to discuss this with you and @yanokwa before closing it just in case you wanted to do something more than having that example conf file on the repo.

**Comment by lognaturel** [comment]
Got it! Then I think we can close. That file will be packaged as `logback.xml` for releases and so we should be able to ask users for their logs as needed.
