### ISSUE TITLE
Difference in export performance between GUI/CLI

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#523]
#### Software versions 
Briefcase v1.11.x

#### Problem description
According to https://github.com/opendatakit/briefcase/pull/457#issuecomment-393905102, there seems to be a performance difference between a CLI export and a GUI export. 

@ggalmazor has not been able to reproduce. @dcbriccetti can you? And if so, can you explain why there is a performance difference?

**Comment by dcbriccetti** [comment]
@ggalmazor, is this still true?

**Comment by ggalmazor** [comment]
I don't know... I couldn't reproduce such a big difference as the one @kkrawczyk123 reported (10m vs 1m). In my host machine, it was just some seconds slower.

If you run it and don't find such a difference, I guess we could dismiss this issue...

**Comment by dcbriccetti** [comment]
So far, I’m seeing differences, too. I’ll investigate.

```
GUI: [Thread-4] INFO  o.o.briefcase.export.ExportToCsv - Exported in 00:00:56...
CLI: [main]     INFO  o.o.briefcase.export.ExportToCsv - Exported in 00:00:33...
```
