### ISSUE TITLE
Status in Detailed Transfer Status window should live-update

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#53]
#### Software versions 
Briefcase v1.4.9

#### Problem description
The status in the Detailed Transfer Status window is not updated as the transfer status changes.

#### Steps to reproduce the problem
1. Select a form
1. Click 'Push' or 'Pull'
1. Click on the 'Details...' button for that form

The Detailed Transfer Status window is opened but it does not update as the transfer status changes.

#### Expected behavior
The Detailed Transfer Status window should be updated as the transfer status changes.

#### Other information 
@carstendev I believe this is why the text area had been made editable.

**Comment by carstendev** [comment]
@lognaturel I'm on it.
