### ISSUE TITLE
Selection highlight should extend behind the Details... button

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#54]
#### Software versions 
Briefcase v1.4.9, Java 1.8.0_112-b16, macOS 10.12.3

#### Problem description
<img width="601" alt="screen shot 2017-01-11 at 9 56 00 am" src="https://cloud.githubusercontent.com/assets/967540/21853297/8f3c0df0-d7e4-11e6-925e-aae7a33501b2.png">

#### Steps to reproduce the problem
Click on a form row.

#### Expected behavior
The row highlight should continue under the button.

**Comment by carstendev** [comment]
**Platform**

Windows 10

**Software versions**

Briefcase v1.4.10

**Behavior**

![selected_row cropped 1](https://cloud.githubusercontent.com/assets/14132179/22865450/36cf0f6a-f165-11e6-90ae-16fdaff5d3b6.png)

@lognaturel This is how it looks on Windows, is this the expected behavior?

**Comment by lognaturel** [comment]
@carstendev Wow, it didn't even occur to me that it might be a platform-dependent issue. Yes, that is what I would expect.

**Comment by rclakmal** [comment]
@lognaturel On OS X. Will try to work on this :)
