### ISSUE TITLE
Export to CSV results in empty CSV

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#544]
#### Software versions 
Briefcase v1.11.0

#### Problem description
Exporting to CSV in v1.11.0 results in a CSV with just the headers.

#### Steps to reproduce the problem
* Clear prefs
* Import from Collect odk storage folders
* Export to CSV

#### Expected behavior
Export CSV has more than header rows.

#### Other information 
Briefcase v1.10 works great, so this is a bug introduced in v1.11

**Comment by ggalmazor** [comment]
@opendatakit-bot claim

**Comment by ggalmazor** [comment]
I've been able to reproduce this by pulling a form that doesn't follow the standard pattern for instanceID, which produces values like this one: `uuid:01234567-0123-0123-0123-012345678901`.

Each submission is stored inside a directory with a sanitized version of its instanceID. In the example above, it the submission would be located at `instances/uuid01234567-0123-0123-0123-012345678901`.

While collecting the submissions that are going to be exported, Briefcase filters out any directory that doesn't match that pattern, which will keep any submission with arbitrary instanceIDs out of the output file.

I guess we should remove that filter to allow any format of instanceID to be used and filter out just what we positively know that it can't be a submission folder, like the `.DS_Store` directories macs leave across the filesystem.

What do you think, @yanokwa, @lognaturel?

**Comment by yanokwa** [comment]
Only submissions pulled from Aggregate have that format. 

When you pull a form from Collect, the folders will be `FORM TITLE_2017-12-23_11-17-33` and have `submission.xml` in them. I'm not a big fan of a wide open filter. We should use the same filtering that previous versions of Briefcase used and add things that are known bad (e.g., .DS_Store).

And we should also add a test to make sure we don't run into this issue again.

**Comment by ggalmazor** [comment]
Another possible scenario: if somehow a submission with instanceID `cocotero-123` gets to Aggregate, Briefcase will create a directory `cocotero-123` with the `submission.xml` inside, 

Ultimately, the instanceID is generated by its binding and the form designer can use any function for that, not just `calculate="concat('uuid:', uuid())"`

**Comment by ggalmazor** [comment]
The previous version only checked that the `File` was a directory and it had a `submission.xml` file in it, which means that adding the extra filtering of hidden directories is a little improvement on top of that.

**Comment by yanokwa** [comment]
I've done a sanity check looked at v1.4.6_Production to see what happens. It seems like the export back then was based on submission.xml. I also quickly looked at the pull from Collect (`TransferFromODK.java`) and there haven't been any major changes in what gets pulled.

**Comment by ggalmazor** [comment]
That makes sense to me
