### ISSUE TITLE
CLI shouldn't be so picky about the storage dir

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#553]
#### Software versions 
Briefcase >v1.10.x

#### Problem description
We want to be rigorous and explicit, but previous versions were more tolerant. We chose to be restrictive because it felt wrong that Briefcase would go creating storage dirs in the user's filesystem.

It turns out that many users rely on this to pull forms using CLI ops and it could represent a burden for them to have actual full storage directories to be able to run those commands.

Briefcase CLI ops could create and prepare storage dirs instead of failing.

#### Steps to reproduce the problem
Run a CLI op with a `-sd` that would produce a non existing location for the briefcase dir.

#### Expected behavior
Gracefully recover instead of failing.

#### Other information 
N/A

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs discussion"

**Comment by lognaturel** [comment]
> We chose to be restrictive because it felt wrong that Briefcase would go creating storage dirs in the user's filesystem.

Next time let's make sure those decisions are brought up for discussion (apologies if I missed it). Whenever there's a change in behavior, especially if it's to become more strict, we should make sure it's discussed and documented.
