### ISSUE TITLE
Change export default conf UI panel

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#568]
The export panel is starting to be packed with lots of configuration options. Since we need to support more options in the future, we should change the UI to hide the default conf form in order to save some vertical space.

I'd like to propose we reuse the override conf dialogs to show the default conf form as well. The general idea would be this:

_**Note**: At the end of this issue there's a list of changes from user feedback in the forums_

- When there's no default conf, we show a message and a button to let the user define one:

  ![export - no default conf](https://user-images.githubusercontent.com/205913/42319840-7e10ad38-8053-11e8-9cad-ab5c540d2692.png)

- The user clicks the button and we show the default conf form in a dialog:

  ![export - default conf dialog](https://user-images.githubusercontent.com/205913/42319816-64f2631e-8053-11e8-8f86-f53f32997f8e.png)

- The user sets some default conf and clicks OK. We show a summary of the default export conf params she has set:

  ![export - default configuration](https://user-images.githubusercontent.com/205913/42319724-1e5030e4-8053-11e8-9061-c078c85ee694.png)

- The user can click on the edit button to use the dialog again.

**Changes from [user feedback](https://forum.opendatakit.org/t/briefcase-default-export-configuration-ui/13932):**

- To save vertical space, we won't be showing the conf summary after the user sets one.
- We will simplify the language distinction between "default" and "custom" configurations by removing both adjectives.
- We will reorder the last block of fields this way:
  1. Pull before export
  2. Export media
  3. Overwrite files
- We will review vertical spacing between fields to make coherent groups

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs discussion"

**Comment by ggalmazor** [comment]
Tagging @yanokwa, @lognaturel and @dcbriccetti to start discussing the proposal

**Comment by lognaturel** [comment]
User feedback: https://forum.opendatakit.org/t/briefcase-default-export-configuration-ui/13932
