### ISSUE TITLE
Icon on reload forms from storage location dialog window.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#579]
#### Software versions 
Briefcase v1.11.x, Java v1.x.x, operating system: Ubuntu, MacOS, Windows 

#### Problem description
After clicking on Reload forms from the storage location dialog message is displayed and it has an icon which if different on all 2 systems, screenshots attached:
![screenshot from 2018-07-12 13-29-59](https://user-images.githubusercontent.com/33342488/42630913-dafeecfa-85d8-11e8-838f-2252e260923c.png)
![screenshot from 2018-07-12 13-31-26](https://user-images.githubusercontent.com/33342488/42630916-de45aafc-85d8-11e8-9be4-ba65c022d2b4.png)
![screenshot from 2018-07-12 13-34-51](https://user-images.githubusercontent.com/33342488/42630917-de5f9b06-85d8-11e8-89dd-c1da04f3ffab.png)

I would like to suggest removing it firstly for unifying behavior for all oses and secondly I remember that when the overwrite dialog was added to export tab - we decided to remove a similar icon.

@lognaturel @yanokwa and @ggalmazor 

@opendatakit-bot label "needs discussion"

**Comment by yanokwa** [comment]
I do dislike the icon. @ggalmazor I think we've done this on other dialog, so might be good for a new contributor.

**Comment by kunalmulwani** [comment]
What would be the best way to test this? Do we have a test URL/instance that I can use?

**Comment by ggalmazor** [comment]
Hi, @kunalmulwani!

You could use https://sandbox.aggregate.opendatakit.org (user: administrator, pass: aggregate)

**Comment by kunalmulwani** [comment]
@opendatakit-bot claim
