### ISSUE TITLE
Briefcase is not exporting in Unicode format

### ISSUE THREAD

**Issue by foranastes** [opendatakit/briefcase#593]
ODK-Briefcase version 1.11.2

I'm getting "????????" instead of Unicode characters on the csv file exported using briefcase. The Works well from Direct export from Aggregate Server.

**Comment by yanokwa** [comment]
Hmm. Can you try the version at https://forum.opendatakit.org/t/csv-file-lao-characters-not-showing-after-export-from-odk-briefcase/14075/16 and see if that works better?

**Comment by foranastes** [comment]
**Yeah... That one works perfectly**

**Comment by yanokwa** [comment]
Thanks for confirming. We'll release a hot fix in a few days!
