### ISSUE TITLE
Specify the correct Java image for CircleCI builds

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#596]
#### Problem description
A recent update on the CircleCI image we use to build JavaRosa has bumped it to use Java 10.0.2 (Oracle), which is incompatible with the JaCoCo version our Gradle uses.

This change makes our builds fail.

#### Expected behavior
The build should use Java 8u171 to work correctly

**Comment by lognaturel** [comment]
Same question as on JR - can we also move away from the deprecated code to eventually go back to the latest?

**Comment by ggalmazor** [comment]
The problem is that Briefcase is failing first because there is some incompatibility with the JaCoCo lib Gradle’s using. We could look into upgrading Gradle in case that solves it.
