### ISSUE TITLE
Briefcase doesn't remember pull sources for a form when it doesn't have credentials

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#603]
#### Software versions 
Briefcase v1.11.3

#### Problem description
Given that the remember passwords setting is enabled, when no credentials are required to pull a form from an Aggregate server (maybe the anon account is enough), then after restarting Briefcase, it always asks you to pull the form first before being able to enable the "pull before export" conf param.

#### Steps to reproduce the problem
1. Ensure that the remember passwords setting is enabled
2. Pull a form from an Aggregate server using the anon account (enter no credentials)
3. Close Briefcase
4. Open Briefcase
5. Go to the export tab
6. Open the custom conf dialog for the form you've pulled on step 2
7. You can't override the "pull before export" conf param

#### Expected behavior
You should be able to override the "pull before export" param on step 7 because you pulled it on step 2

#### Other information 
The key to the solution of this issue is in `ExportForms.java` line 71:
```java
if (appPreferences.hasKey(urlKey) && appPreferences.hasKey(usernameKey) && appPreferences.hasKey(passwordKey))
  transferSettings.put(formId, new ServerConnectionInfo(
      appPreferences.nullSafeGet(urlKey)
          .orElseThrow(() -> new RuntimeException("Null value saved for " + urlKey)),
      appPreferences.nullSafeGet(usernameKey)
          .orElseThrow(() -> new RuntimeException("Null value saved for " + usernameKey)),
      appPreferences.nullSafeGet(passwordKey)
          .orElseThrow(() -> new RuntimeException("Null value saved for " + passwordKey)).toCharArray()
  ));
```

This block doesn't contemplate the possibility of having a URL but no username/password pair.

**Comment by ggalmazor** [comment]
@opendatakit-bot label "good first issue"
@opendatakit-bot label "help wanted"

**Comment by kunalmulwani** [comment]
@ggalmazor is there a test instance that I can use to reproduce this issue?

**Comment by ggalmazor** [comment]
Hi, @kunalmulwani! You can use https://sandbox.aggregate.opendatakit.org/Aggregate.html

Try pulling from there without specifying user/pass.

Also, if you're planning on working on this one, you can claim it with `@opendatakit-bot claim`

**Comment by kunalmulwani** [comment]
@ggalmazor Thank you. I was just analyzing the issue before working on it. I wanted to know if we can keep the username pass as null in case they are not present. Please advise.

**Comment by kunalmulwani** [comment]
@ggalmazor Can you please advise on this?

**Comment by ggalmazor** [comment]
Hi, @kunalmulwani!

If you've already started working on this one, could you tell me about what have you tried, or where are you stuck, so that I can make an idea of your current scenario?

**Comment by kunalmulwani** [comment]
Hi @ggalmazor!

I have tried using <code>appPreferences.get()</code> instead of <code>nullSafeGet</code> with default value as null. I am not sure if this is the right way to do this.

**Comment by ggalmazor** [comment]
Hi, @kunalmulwani!

All new code should always use `.nullSafeGet()` (I should add the `@Deprecated` annotation and document this on the code, sorry about that).

I suggest you start by copying and pasting the `if` block from `ExportForms.java`, line 71 (the one in the issue description) and adapt it to the new case we want to cover: we have the URL **and** we don't have a username **and** we don't have a password.

When this condition is met, we should put into the `transferSettings` map a new `ServerConnectionInfo` that has the URL and null username and password.

**Comment by kunalmulwani** [comment]
@ggalmazor I can't see any forms to pull from https://sandbox.aggregate.opendatakit.org

**Comment by ggalmazor** [comment]
@kunalmulwani the sandbox server gets wiped every Sunday. Eventually, someone will push something :) 

You can push some if you want.

**Comment by ggalmazor** [comment]
(I've pushed some forms :smile:)

**Comment by kunalmulwani** [comment]
@ggalmazor Thank you. I tried updating the logic and followed the steps. But in appPreferences has the password even though I haven't set it explicitly.

**Comment by kunalmulwani** [comment]
@opendatakit-bot claim

**Comment by kunalmulwani** [comment]
@ggalmazor Can you think of any scenario where I can find the password in appPreferences?

**Comment by kunalmulwani** [comment]
@ggalmazor When I try to pull a form anonymously with remembering passwords settings enabled, I should ideally get null for username and passwords in <code>appPreferences</code>. I get null for username but I can see that <code>appPreferences</code> has an entry for the password. Any idea about this? Why does the <code>appPreferences</code> has an entry for password for anonymous account?

**Comment by ggalmazor** [comment]
That seems like some residual information from a previous pulling operation. I would care much about it because the condition must check that *both* are empty. You can use:

```java
appPreferences.hasKey(usernameKey); // Should be false
appPreferences.nullSafeGet(usernameKey).isEmpty(); // Should be true
```

I'm thinking now that the safest way to check this would be the one in the second line from the example above. We could have a username key with a null value.

**Comment by kunalmulwani** [comment]
@ggalmazor  <code>passwordKey</code> is an empty string. I couldn't find the <code>isEmpty()</code> method. Should I add one?

**Comment by ggalmazor** [comment]
I see in your screenshot that the result of `appPreferences.nullSafeGet(usernameKey)` is an `Optional` instance, which has the `isEmpty()` method. The problem is that the optional you are getting is not actually empty (it's holding a non-null string).

I think this would work in this case: `appPreferences.nullSafeGet(usernameKey).filter(value -> !value.isEmpty()).isEmpty(); // should give true in your example`

**Comment by kunalmulwani** [comment]
The screenshot is for <code>passwordKey</code>. <code>usernameKey</code> is null.

**Comment by ggalmazor** [comment]
OK, but I'd suggest filtering both anyway

**Comment by ggalmazor** [comment]
Sorry, I didn't read correctly your message. You're talking about the password*Key*.

**Comment by kunalmulwani** [comment]
I have just added a basic logic that is expected to work. `usernameKey and passwordKey` should not be present. [Commit](https://github.com/kunalmulwani/briefcase/commit/c7485ad6763ff7384419ba71960d90689ce58b22)

**Comment by ggalmazor** [comment]
Thanks, @kunalmulwani! With the code I'll be able to understand it better. I'll check it tomorrow.

**Comment by ggalmazor** [comment]
Hi, @kunalmulwani!

Your commit is looking good :)

Does it solve the original issue?

**Comment by kunalmulwani** [comment]
@ggalmazor nope. This is expected to work but like I said we have an empty value for `passwordKey` in `appPreferences`.

**Comment by ggalmazor** [comment]
Could you try this?

```java
if (appPreferences.nullSafeGet(urlKey).filter(s->!s.isEmpty()).isPresent()
          && !appPreferences.nullSafeGet(usernameKey).filter(s->!s.isEmpty()).isPresent()
          && !appPreferences.nullSafeGet(passwordKey).filter(s->!s.isEmpty()).isPresent())
        transferSettings.put(formId, new ServerConnectionInfo(
            appPreferences.nullSafeGet(urlKey)
                .orElseThrow(() -> new RuntimeException("Null value saved for " + urlKey)),
            null, null
        ));
```

**Comment by kunalmulwani** [comment]
@ggalmazor it works.

**Comment by ggalmazor** [comment]
OK, this leads me to think that we should refine those `.hasKey()` methods to do this filtering inside, but I think you could create a PR with this and any improvement you'd want to add.
