### ISSUE TITLE
Make headers separators more visible.

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#610]
#### Software versions 
Briefcase v1.11.x, Java v1.8.x, operating system: Windows 10

#### Problem description
I think that horizontal and vertical separators of the forms table's header row could be more visible on the Windows system on all Pull, Push and Export tabs. It is not a high priority issue just a small visual improvement. 
Screenshot attached: 
![screenshot from 2018-08-21 10-02-24](https://user-images.githubusercontent.com/33342488/44390082-bf370c00-a52c-11e8-8db3-783ee22896b2.png)

#### Steps to reproduce the problem
1. Run briefcase on windows os.

**Comment by ggalmazor** [comment]
@opendatakit-bot label "good first issue"

**Comment by ggalmazor** [comment]
The `FindDirectoryStructure` class has a method `isWindows()` that could be useful for this one ;)

**Comment by huangyz0918** [comment]
@ggalmazor Can I work on this ?
@opendatakit-bot claim

I think in macOS the header could be more visible too, maybe we can add a background on that, what do you think? @ggalmazor

**Comment by dcbriccetti** [comment]
Increasing the header font size may be a simple way to improve the appearance. Here’s an increase by 1.3 times on Mac:

Before:
<img width="495" alt="screen shot 2018-08-25 at 1 03 58 pm" src="https://user-images.githubusercontent.com/55099/44622162-32f85200-a868-11e8-8c6c-4ea8a3093e14.png">

After:
<img width="490" alt="screen shot 2018-08-25 at 1 04 55 pm" src="https://user-images.githubusercontent.com/55099/44622165-40154100-a868-11e8-8806-f03b3bf111c9.png">

With the row height explicitly set to 28 pixels, and the gear icon  being much larger than the default header font size, the header is dwarfed by the rows.

@huangyz0918, maybe you can try this change and paste in what it looks like on Windows.
