### ISSUE TITLE
Export button is disabled after first pull because no default configuration is set

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/briefcase#628]
After a user has pulled some forms, they will often want to export those forms. Now that the default configuration is hidden behind a button, it's not as clear that they need to set values there. They may check a form, try to tap the Export button and find that they're stuck. Nothing indicates that the problem is that there's no configuration set.

Some options:
- when a form is selected, if no default configuration is set, add text in a dialog or above the set configuration button to indicate a configuration is required
- enable the export button but when it's clicked, show a dialog indicating a configuration is required

I can see this being a dead end for users so we may want to address it before the release?

**Comment by ggalmazor** [comment]
I like the idea of enabling the export button and showing a dialog. We could tell the user what's missing. It might be the output dir, or it might be that she hasn't selected any form yet. In future releases, we could even warn about missing private keys for encrypted forms!

Having a default configuration is not strictly required. It would be OK to have a custom conf defined for every selected form, and that would enable the button in the current build.

**Comment by lognaturel** [comment]
Ahh, right, there are lots of ways to get out of that state.

Agreed that always enabling the export button and then giving some hints on how to proceed if not enough information is set seems like a good approach.

**Comment by ggalmazor** [comment]
OK, I'll work a PR tomorrow with this. It should be easy to do since we already have an `ExportConfiguration.getErrors()` that would give us the information we want to show in the dialog

**Comment by lognaturel** [comment]
Sounds great! That will give @yanokwa a bit to see if he has any other thoughts on this.
