### ISSUE TITLE
Unified UI

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#64]
ODK Briefcase is a Java application for fetching and pushing forms and their contents. It helps make data from millions of ODK campaigns portable. On first launch, Briefcase currently displays a screen with a description of the program and its functionality. One part of this project will involve rethinking how a user gets to know how Briefcase works and sets up a Briefcase storage directory.

Additionally, Briefcase is separated into four utilities: 
- the main one which is used to push, pull and export form instances
- a preference clearer for the main utility
- a character set converter for CSVs
- a blank form uploader

Currently, only the main utility is packaged for release so the other ones are not accessible by non-developers. Having a single application will make the secondary functionality usable by a broader range of users. The UX challenge here will be making the functionality clear to users and logically connecting it together.

Bonus: Add the ability to convert forms from XLSForm to [XForms](https://github.com/opendatakit/xforms-spec), probably by using [pyxform](https://github.com/XLSForm/pyxform) (Python).

**Comment by techfreakworm** [comment]
Hello,
I have an idea for improving UX for a clear understanding of the functionalities.
Idea is to have translucent JFrames in Oval or Circular shapes just above the function/title/any other attribute of which demo is to be given.
[Example of transparent JFrame.](https://docs.oracle.com/javase/tutorial/uiswing/misc/trans_shaped_windows.html)
A guided demo will be there, information of which would be provided with translucent windows.
Should I prepare a UI Mock using Image editing tools or using JAVA API?

**Comment by yanokwa** [comment]
@techfreakworm The most important thing is the improving the user experience from first launch and through the pull/push/export workflow. Start by using the app first, then sketch out low fidelity mockups, and post those for feedback.

**Comment by rclakmal** [comment]
@yanokwa 
I came up with this intro step mockups to introduce briefcase and functionality to new users. 
[ODKBriefCase UX.pdf](https://github.com/opendatakit/briefcase/files/821660/ODKBriefCase.UX.pdf)

Let me know your feedback. In the mockups, there would be "image not found" containers. My idea is we can place some gif/video to guide users on how to use the functionality. 

Something like this..
![odk](https://cloud.githubusercontent.com/assets/794011/23617600/e6bad22c-028d-11e7-99ff-5b07081386e8.gif)

**Comment by yanokwa** [comment]
@rclakmal For an application this straight-forward, I'm not sure a first run tutorial is needed. If you were to re-work the entire user experience, how would you restructure it to make it more intuitive without requiring a first run tutorial?

**Comment by rclakmal** [comment]
@yanokwa Thanks. I understand your argument. 

At this point, I have couple of questions before moving forward...
Do you have any comments in the past from actual users about the user experience of push/pull/export windows? And do the target user group for briefcase are they presumed to be familiar with the concept of push/pull/export?  Also, how many active users do we have for this desktop app? any demography data about the users?

**Comment by Giannis13T** [comment]
Hello,
The idea I came up with to help users better understand the functionalities of the application is a "Help" JButton. When the user clicks on the button it will prompt a new window showing imformation (using HTML) about pull/push/export as well as general information about what briefcase is.
Also, we could show a small information message when the user hovers over an item to indicate what the item is used for.
Please let me know what you think of my idea.

**Comment by yanokwa** [comment]
@Giannis13T For an application this straight-forward, I'm not sure a help button is needed. If you were to re-work the entire user experience, how would you restructure it to make it more intuitive?

**Comment by yanokwa** [comment]
He's an ideal to get the discussion moving. I wonder if we can simplify the abstraction even farther. So why not UX that's built more like an FTP/client. So you have a list of forms on the server on one side, and the list of forms on the other side. If you select server side forms, you can then download them. If you select local forms you can export or push.

This is a screenshot from an FTP client. Hopefully it helps get the idea across.
<img width="792" alt="screen shot 2017-03-15 at 12 31 55" src="https://cloud.githubusercontent.com/assets/32369/23959623/0479eac4-097c-11e7-87bb-58d887ad21f6.png">

**Comment by Giannis13T** [comment]
I will agree that this is a lot simpler and better to help the user get familiar with briefcase. If the pattern in the image you posted is used, I would also suggest that we use a text area below the lists to show the details of the pull/push/export procedure, so as not to include the "details" button next to every form.

**Comment by rclakmal** [comment]
With addition to the discussion at slack, also posting the couple of mockups I came up for further feedback and discussion from other students and project members..

`Option with action buttons and checkboxes. `
![withiconsandcheckboxes](https://cloud.githubusercontent.com/assets/794011/23977721/1dcfb462-09f0-11e7-92ae-7b0bf0036794.png)

`Option with drag & drop for push/pull and a "right click menu" for other options`
![withrightclickmenu](https://cloud.githubusercontent.com/assets/794011/23977722/1dd30392-09f0-11e7-9a96-7f72800aa075.png)

**Comment by yanokwa** [comment]
@rclakmal I like the first one because being able to select multiple forms at once is important, but we should have right-clicking on individual forms like the second one. 

ODK Briefcase also has the ability to pull data from an SD card (which is local). Can you try mocking that up using this two-pane system as well?

I agree with @Giannis13T that we'll need some sort of place in the UI that prints out details.

**Comment by rclakmal** [comment]
@yanokwa and all, 
I believe we could keep the form source selection somewhat similar to the existing UI. On top of the two-pane system, you have a **connection panel**, which always contains a drop-down box as the first UI element with all the input sources (aggregator, mounted sd card) as choices. The second line of UI elements will dynamically change as per the drop down selection. 

`With Aggregator`
![withaggregratorassource](https://cloud.githubusercontent.com/assets/794011/24024375/3211abce-0ab3-11e7-98b2-edf013b15e67.png)

`With Mounted SD card`
![withsdcardassource](https://cloud.githubusercontent.com/assets/794011/24024380/3d92f98a-0ab3-11e7-84eb-a4983a467fc7.png)

**Comment by rclakmal** [comment]
As for the details, why don't we simply provide a `details` action button and then create a `popup dialog`. This will allow the user to check out details for multiple forms in a single go. 

![detailsdialog](https://cloud.githubusercontent.com/assets/794011/24024424/a1403e20-0ab3-11e7-86fb-932602c8b976.png)

**Comment by rclakmal** [comment]
@yanokwa and @lognaturel 
Could you pls explain a little bit about the use cases of 3 sub-functionalities?

- Preference clearer for the main utility (I guess this to clear the briefcase storage location? )
- Character set converter for CSVs -
- Blank form uploader

**Comment by icemc** [comment]
@yanokwa  it will be great to know the functionality of the other utilities. As @rclakmal requested, since it will help the developer know where to place them in the UI design.

**Comment by rclakmal** [comment]
@icemc In the #briefcase-code slack channel, there are some information about these 3 sub utilities provided by @yanokwa and @lognaturel. Have a look :-)

**Comment by icemc** [comment]
@rclakmal  thanks will have a look

**Comment by lognaturel** [comment]
@rclakmal @icemc Good question. Just so we also have it here for future reference:
- No one seems to remember why the preference clearer was made a separate thing. It seems it could easily be a "reset all" button in settings. This won't even make much sense until there are more settings to clear.
- See [this thread](https://groups.google.com/forum/#!msg/opendatakit-developers/uozMAr0LcpA/nSavMnzxyRkJ) for information about the character set converter
- See [this page](https://opendatakit.org/use/form-uploader/) for information about the form uploader

**Comment by ggalmazor** [comment]
I don't know if this issue is still relevant, since it was to support a gsoc'17 candidacy.

**Comment by yanokwa** [comment]
Agreed that it's not longer relevant.
