### ISSUE TITLE
Decryption failing without a log

### ISSUE THREAD

**Issue by MartijnR** [opendatakit/briefcase#645]
#### Software versions 
Briefcase v1.12.0, Java v9.01, MacOS

#### Problem description
Decryption (via export) failing without apparent log generation. This could be a loggin bug, or just a request to guide me in finding logs.

#### Steps to reproduce the problem
I am implementing encryption in Enketo and so far failing to decrypt with ODK Briefcase. Probably some subtle issue but at this point in order to proceed I could use some insight into why it fails.

1. I copy the submission.xml manifest file and the submission.xml.enc file manually into the ODK Briefcase storage folder (under the form subfolder in the instances folder under its own uuid folder). Note I can successfully decrypt pulled ODK Collect submissions for the same form.
2. I click export in ODK Briefcase
3. I see a dialog "Unexpected error. See logs".

#### Expected behavior
Logs to be output to a file.

**Comment by lognaturel** [comment]
To confirm, there's no `briefcase.log` file that is a sibling of the `jar` file?

**Comment by MartijnR** [comment]
That correct. There isn't one (there was one generated during installation and perhaps initial pulling) but after deleting it and testing exports, a new one is not being generated.

**Comment by lognaturel** [comment]
Interesting. And if you pull or launch again, then does it get created? @ggalmazor is likely to know more off the top of his head so I'm inclined to give him some time to get back to you on this.

**Comment by MartijnR** [comment]
Aha! I restarted ODK Briefcase and this generated a new briefcase.log! After hitting export it is now populating with useful logs!

So it was an odd case, where the briefcase.log file is deleted while ODK Briefcase is open!

Thanks!

**Comment by lognaturel** [comment]
🎉 🎉 Thought that could be the case! I think this is normal behavior for our logging libraries.

> and sorry to break everything

Wait, what have you broken?! 🤔 😄

**Comment by ggalmazor** [comment]
I’m happy that y’all figured it out! :)

I’d like to keep the issue around for some days, though, in case we can improve the log conf to recover from that situation gracefully.

**Comment by ggalmazor** [comment]
After thinking about this, I don't have any clever way to prevent this kind of issues. 

At least we can improve the docs and explain how logs work. Closing in favor of https://github.com/opendatakit/docs/pull/898
