### ISSUE TITLE
Value of PARENT_KEY column does not exist in corresponding KEY column

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/briefcase#646]
In some cases, it seems that after export, a repeat group CSV file can have a value in its `PARENT_KEY` column that does not exist in the corresponding `KEY` column. For example, suppose that a form has a single repeat group `r`, which is nested within a few non-repeat groups:

* `g1` (group)
  * `g2` (group)
    * `g3` (group)
      * `r` (repeat group)

Suppose that the form has a single submission, and the value of the `KEY` column in the main CSV file is `uuid:519284a9-4fd5-46c1-bbfc-56e1bf0ac4ba`. I think the value of the `PARENT_KEY` column in the repeat group CSV file should be the same value: `uuid:519284a9-4fd5-46c1-bbfc-56e1bf0ac4ba`. However, right now it seems to include the group names: `uuid:519284a9-4fd5-46c1-bbfc-56e1bf0ac4ba/g1[1]/g2[1]/g3[1]`.

I see the expected behavior in Briefcase 1.10.1, but I think I'm seeing group names in `PARENT_KEY` in 1.11.0, as well as the latest version, 1.12.0. I'm also sharing an example form and submission with @ggalmazor in case that's helpful.

This issue emerged from a forum post about `odkmeta`: https://forum.opendatakit.org/t/odk-meta-repeat-groups-not-merging/15308. `odkmeta` doesn't make assumptions about the format of `KEY` or `PARENT_KEY`, but it does require every value of a `PARENT_KEY` column to exist in the corresponding `KEY` column.

**Comment by ggalmazor** [comment]
Thanks, @matthew-white! It looks like we have a bug in the algorithm that builds the parent keys.
