### ISSUE TITLE
Encrypted submissions with more than 1 media file are not exported correctly

### ISSUE THREAD

**Issue by MartijnR** [opendatakit/briefcase#653]
#### Software versions 
Briefcase v1.12.0, Java v9.0.1, Mac OS 10.13.6, Aggregate v1.6.1, Collect v1.17.0

#### Problem description
Encrypted records with 2 uploaded photos are successfully pulled to Briefcase, but when exporting there are 2 issues (probably related):

1. Only the first of the uploaded photos ends up in the Briefcase export media folder
2. For records with 2 photos, `isValidated` is always `false` in the CSV table.

#### Steps to reproduce the problem
1. Use [encrypted.xml.txt](https://github.com/opendatakit/briefcase/files/2420707/encrypted.xml.txt) and replace public key with your own
2. Use ODK Collect 1.17.0 to submit a record with 2 photos to Aggregate 1.6.1 
3. Pull the record with ODK Briefcase 1.12.0
4. Note that both encrypted photos get pulled successfully by checking the `instances` folder.
5. Export the record and inspect the export directory.

#### Expected behavior
1. for all media files to be present in the export directory under media
2. for `isValidated` to be `true` in the CSV file

**Comment by ggalmazor** [comment]
I think I found the bug!

Briefcase is expecting a list of `file` nodes inside the `media` node but, instead, it's getting this:
```xml
<media>
  <file>1538036287659.jpg.enc</file>
</media>
<media>
  <file>1538036295850.jpg.enc</file>
</media>
```

I'll start factoring a fix right away.

**Comment by MartijnR** [comment]
Aha, i was wondering about that actually! Great.

**Comment by ggalmazor** [comment]
@MartijnR, it would be great if you can test it with the changes I've pushed to #655

Having you confirm that the PR solves the issue would be enough sanity checking to release it as a patch version v1.12.1 today or tomorrow.

**Comment by MartijnR** [comment]
@ggalmazor I'd be happy to do that. I'm not a Java person, though, and trying to compile Briefcase will be beyond my capacity. Any chance you can pass me a compiled file?

**Comment by ggalmazor** [comment]
Of course, you can use this one: 
[briefcase.zip](https://github.com/opendatakit/briefcase/files/2425046/briefcase.zip)

**Comment by yanokwa** [comment]
> Trying to compile Briefcase will be beyond my capacity.

I believe in you, @MartijnR. 😂

**Comment by ggalmazor** [comment]
That's strange, @MartijnR... I can't reproduce any problem with the nicer syntax. 

I believe Collect doesn't generate that syntax, though.

**Comment by MartijnR** [comment]
Here is the whole ODK Briefcase folder including private PEM with just one instance to help troubleshooting.
[ODK Briefcase.zip](https://github.com/opendatakit/briefcase/files/2425479/ODK.Briefcase.zip)

Note this submission was generated by Enketo, but it works well if I use ODK Collects /media/file syntax. Also note that the signature is still under development but that probably has no influence.

Judging from the failed_submission_1.xml file, it seems the issue is related to the logic that increments the initialization vector.

Logging doesn't seem to be working in this build. I tried removing the old briefcase.log and restarting.

Let me know if I can send anything else!

**Comment by MartijnR** [comment]
Ignore last message! I messed up. Let me re-do!

**Comment by MartijnR** [comment]
Alright, it wasn't me who messed up. I now have proof that Aggregate (or else Briefcase) strips the second file element from a media element.

So I'd say, let's not fight it, and use what Collect is using :)

**Comment by lognaturel** [comment]
Ahhh, ok. So to be super explicit, Briefcase can correctly export that structure as verified by @ggalmazor's test and our manual verification but it gets modified before it actually gets to the Briefcase storage directory?

**Comment by MartijnR** [comment]
Yes, indeed. I just confirmed that when manually copying the instance files (bypassing Aggregate) works well in Briefcase with the nicer syntax.

**Comment by ggalmazor** [comment]
Then we can move this one to an issue for Aggregate, I suppose. Even if it's only to document this behavior.

**Comment by lognaturel** [comment]
Ok, great. So let's file an issue to hunt that down.

Doing a quick pass over #653 and we can merge.

**Comment by ggalmazor** [comment]
Hi, @MartijnR! We've release [v1.12.1](https://github.com/opendatakit/briefcase/releases/tag/v1.12.1) with the fix for this bug :)

**Comment by MartijnR** [comment]
Great! Thanks for fixing this so quickly!
