### ISSUE TITLE
Fix split select multiples for forms using search() as external source of items

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#656]
#### Software versions 
Briefcase v1.12.0

#### Problem description
As discussed in https://github.com/opendatakit/docs/pull/871#discussion_r221159602, forms that use external csvs combined with `search()` appearance don't really work (I'll create an issue on briefcase to track this).

Take this form, for instance: [search_and_select.zip](https://github.com/opendatakit/docs/files/2427166/search_and_select.zip)

You get this CSV export:
```csv
SubmissionDate,fruit,fruit/name_key,note_fruit,meta-instanceID,KEY
28-sep-2018 9:21:04,mango oranges,0,"",uuid:4151c9a4-0f86-47a1-b434-9f69f0309028,uuid:4151c9a4-0f86-47a1-b434-9f69f0309028
```

- There's actually a static item:

  ```xml
  <select appearance="search('fruits')" ref="/search_and_select/fruit">
    <label>Choose a fruit</label>
    <item>
      <label>name</label>
      <value>name_key</value>
    </item>
  </select>
  ```
- This static item produces the extra `name_key` column in the output CSV.
- At least we're not getting the choices in the external CSV file as static choices.

#### Steps to reproduce the problem
Pull the attached form (via Aggregate) and export it having enabled the "Split select multiples" export conf param. There's no need for sending submissions.

#### Expected behavior
No extra column `name_key` should be present in the output CSV file.

#### Other information 
We could exclude fields that use the `search()` appearance function.

**Comment by lognaturel** [comment]
👍 Excluding fields that use `search()` sounds good.
