### ISSUE TITLE
Resume last pull

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#681]
Users with big forms and/or many submissions (10k, 25k, and more), often complain about how much time the pulling and exporting processes take to complete.

([forum conversation](https://forum.opendatakit.org/t/pull-submissions-starting-from-date/16200))

This problem can be worse in scenarios where users have a long-living form that receives periodically new submissions i.e. to receive the last 100 submissions, Briefcase has to navigate through the first 10k to reach them.

(note that Briefcase doesn't actually download the 10k submissions it already pulled before, see the explanation below)

Some insights about how Briefcase pulls forms and their submissions from Aggregate:
- Briefcase pulls data from Aggregate in batches of a maximum of 100 submissions each.
- A batch consists of an XML  with:
  - A list of submission instance IDs
  - A "cursor" that can be used to get the next batch
- A cursor is an XML with:
  - The field used to order submissions. Currently, we're using `LAST_UPDATE_DATE`
  - The last update date (ISO8601) of the last submission from the previous batch
  - The instance ID of the last submission from the previous batch
  - A boolean telling if the cursor is a forward cursor

  ```xml
  <cursor xmlns="http://www.opendatakit.org/cursor">
    <attributeName>_LAST_UPDATE_DATE</attributeName>
    <attributeValue>2018-11-07T14:43:24.644+0000</attributeValue>
    <uriLastReturnedValue>uuid:d9b67b6f-2058-469b-8cb1-c86b9c34b632</uriLastReturnedValue>
    <isForwardCursor>true</isForwardCursor>
  </cursor>
  ```
- In order to get the first batch of submissions, Briefcase sends Aggregate an empty cursor
- Briefcase will continue asking for more batches until an empty batch arrives, which ends the pull operation

(now this is what happens with each non-empty batch received)
- Each batch will contain a maximum of 100 submission instance IDs. 
- Briefcase uses a local database to exclude from the list any submission that's been already downloaded
- For each of those remaining submission instance IDs, Briefcase downloads them from Aggregate, including all their media attachments

**Optimization problem**

Taking how Briefcase works into mind, in scenarios like the one described above, where a long-living form receives new submissions periodically, Briefcase will be forced to "scan" all the submission instance IDs until it reaches a batch where new submissions start to show up.

For a form with 10k submissions, this means 100 requests before reaching a batch that actually contains new submissions. That has a negative impact on the overall performance of the operation and the monthly expenses for users hosting their Aggregate instances in App Engine.

**Proposed solution**

- Briefcase stores the last cursor used for each form
- We add a checkbox to "Always try to resume pulls" in the Settings tab
- When that's enabled, Briefcase sends the stored cursor instead of an empty one, effectively resuming the pull operation.
- Briefcase should also provide a new CLI flag to enable this feature for users launching Briefcase from the command line

**Comment by yanokwa** [comment]
@ggalmazor Can you send in a WIP PR for this when you get a chance?
