### ISSUE TITLE
Make aggregate's URL clickable

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#688]
#### Problem description or more improvement suggestion
I was wondering if we could do aggregate's URL clickable on the pull and push tab or at least make it possible to copy. 
It currently looks like: 
![screenshot from 2018-11-28 11-26-39](https://user-images.githubusercontent.com/33342488/49145625-7e574c00-f300-11e8-82c7-971b5475d2b4.png)
![screenshot from 2018-11-28 11-21-57](https://user-images.githubusercontent.com/33342488/49145628-7eefe280-f300-11e8-9df2-1564399786c7.png)
I think that hyperlink would be a very comfortable solution. It would also make an URL more visible in comparison to the other visible text because now it is not distinguishable nearly at all.
@yanokwa @ggalmazor what are your thoughts on that?

**Comment by ggalmazor** [comment]
+1

**Comment by yanokwa** [comment]
Any reason why this isn't a good first issue, @ggalmazor?

**Comment by ggalmazor** [comment]
Huh! I removed that one by accident while applying `enhancement`
