### ISSUE TITLE
error on pulling a form with guidance hint but without an hint

### ISSUE THREAD

**Issue by aurdipas** [opendatakit/briefcase#699]
#### Software versions 
Briefcase v1.13.1, Java version "1.7.0_80", operating system Windows 7, Aggregate v1.7.1

#### Problem description
I've a form on aggregate that contains some guidance hints, but without a regular hint like in the picture, when I try to pull the form I get the following error message:

"Fetching form definition
resolving against briefcase form definitions
Error parsing form definition: org.opendatakit.aggregate.exception.ODKIncompleteSubmissionData: Javarosa failed to construct a FormDef. Is this an XForm definition?"

![image](https://user-images.githubusercontent.com/5656097/52286911-6f78bf80-2969-11e9-9bd8-b43109343e70.png)

#### Expected behavior
the form should be pulled successfully.

#### Other information 
Adding a regular hint solves the issue.
It looks related to the issue already resolved for pyxform:
https://github.com/XLSForm/pyxform/issues/225

**Comment by ggalmazor** [comment]
Hi @aurdipas! thanks for reporting the issue.

Briefcase currenlty runs JavaRosa 2.11.2, and I'm being able to pull the form if I update JR to the latest 2.13.0. Does this make sense to you?

**Comment by ggalmazor** [comment]
Closed by #701
