### ISSUE TITLE
On export, only create media folder when needed

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#70]
On export to CSV, Briefcase creates a media folder whether or not there is media associated with the file. It should only create a media folder when there is media.

**Comment by shivam-tripathi** [comment]
@opendatakit/briefcase Please review :)

**Comment by yanokwa** [comment]
Hi @shivam-tripathi! I've confirmed this works in the GUI, but it doesn't work in the CLI. 

To find out what the CLI arguments are:
` java -jar "ODK Briefcase v1.4.10-16-g553e235.jar" --help`.

The command I'm using is 
`java -jar "ODK Briefcase v1.4.10-16-g553e235.jar" -ed ~/Desktop/ -id choice_filter -sd ~/Library/Application\ Support/ODK/ -f /tmp/choice_filter.csv`

**Comment by shivam-tripathi** [comment]
I checked. It appears to work fine.
The command I am running is : 
`java -jar "ODK Briefcase v1.4.10-10-g0a250e2.jar" -id N_Biggest -ed "/home/shivam" -sd "/home/shivam" -f "n_biggest.csv"`
