### ISSUE TITLE
Pull all forms when form_id is not specified

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#721]
#### Software versions 
Briefcase v1.14

#### Problem description
There isn't an easy way to pull all forms on a server on the CLI. We should make this possible!

#### Expected behavior
When I run `java -jar ODK-Briefcase-v1.14.0.jar -plla -sd /Users/yanokwa/Desktop -u admin -p admin -url https://example.com` it should pull all forms. 

#### Other information 
This would match the behavior when pulling from Collect.

**Comment by kunalmulwani** [comment]
@ggalmazor @yanokwa  I can work on this but I might need some help.

**Comment by ggalmazor** [comment]
Sure, @kunalmulwani!

You can contact me here or in Slack. You can also create a "work in progress" PR so that I can review while you work on the changes.
