### ISSUE TITLE
Briefcase CLI reports 'Error: with formId xxxx not found' if GUI has not previously built target storage dir

### ISSUE THREAD

**Issue by chrissyhroberts** [opendatakit/briefcase#722]
#### Software versions 
ODK-Briefcase-v1.14.0, java version "10.0.1", OSX 

#### Problem description
If I run a CLI call to pull data from aggregate to a fresh directory which has not previously been used, briefcase reports `Error: with formId xxxx not found`
If I then open the Briefcase GUI and initiate a pull, the storage dir is created. After this, subsequent pulls with the CLI work

#### Steps to reproduce the problem
Create a new directory and run a pull with CLI

#### Expected behavior
Failure, with report of form not found

**Comment by ggalmazor** [comment]
Thanks for reporting this, @chrissyhroberts!

**Comment by mayank8318** [comment]
@ggalmazor Is this issue open?

**Comment by ggalmazor** [comment]
It should be solved, but can you try to reproduce, @mayank8318?

If you confirm it can't be reproduced we'll close it :)

**Comment by mayank8318** [comment]
@ggalmazor it is solved. Couldn't reproduce :)

**Comment by ggalmazor** [comment]
Awesome! Thanks, @mayank8318!
