### ISSUE TITLE
Unable to detect SD card in Ubuntu

### ISSUE THREAD

**Issue by shivam-tripathi** [opendatakit/briefcase#73]
Mount location of SD card in Ubuntu has been changed from  `/media` to `/media/username`. We should modify mount locations to include this.

**Comment by yanokwa** [comment]
@shivam-tripathi Good catch! What other mount points do the popular distros use?

**Comment by shivam-tripathi** [comment]
@yanokwa Apart from `/media/username`, I have found Fedora and Arch based flavours using `/run/media/username` as default the mount point.
