### ISSUE TITLE
Briefcase fails to parse forms that have pulldata() expressions

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#741]
This issue must be completed with further data and assets:
- [ ] Provide a simple form that reproduces the error
- [ ] Provide feedback after reproducing the error

#### Software versions 
Briefcase v1.15.0

#### Problem description
User in the forums reports this issue https://forum.opendatakit.org/t/odk-briefcase-error-on-export/20197

#### Steps to reproduce the problem
(pending)

#### Expected behavior
(pending)

#### Other information 
Briefcase 1.14 doesn't show this issue.

**Comment by yanokwa** [comment]
@ggalmazor Do you think we can get this into the next release?

**Comment by ggalmazor** [comment]
It's hard to say, honestly. We're currently working on the feedback of the big PR and still finding minor stuff that's preventing us to release 1.16. Let's wait until Monday/Tuesday and see how it feels.

I'm anticipating a swift v1.16.1 followup anyway. We could get this one there.

**Comment by ggalmazor** [comment]
Closed by #736
