### ISSUE TITLE
Add update notifications to footer for when new versions are released

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#743]
This is hopefully a minor and non-controversial request so I'm putting it here as an issue instead of a forum post.

We should let people know when there are new versions of Briefcase. My preferred approach here would be to do what we do in Aggregate with a non-blocking call to GitHub. In the lower left-hand side of every tab, we put the following:
* Current version: vx.y.z
* Old version: vx.y.z - [Update available](https://github.com/opendatakit/briefcase/releases/latest)

I'd love to see this not in the upcoming release, but in the following one.

**Comment by ggalmazor** [comment]
OK, let me suggest a less intrusive alternative:
- We don't show the current version (it's on the window title)
- We only show the `Update available` link at the bottom of the window if there's an update available. Otherwise, business as usual.
  - The link is clickable

![image](https://user-images.githubusercontent.com/205913/61036262-0e965d00-a3c9-11e9-967b-c8f8ae095776.png)

**Comment by yanokwa** [comment]
I like showing the Update available when there is an update available. I think we need to show the current version somewhere for when people have problems. Maybe the title isn't the best place, but we need to put it somewhere accessible. Maybe settings?

**Comment by ggalmazor** [comment]
Thanks!

Settings is a great place for that. I'll add it there in a new commit

**Comment by ggalmazor** [comment]
OK! This is what I've done so far:
![version and update note](https://user-images.githubusercontent.com/205913/61202754-b329df00-a6e8-11e9-9258-c0ceef628f40.gif)

**Comment by yanokwa** [comment]
IMHO, it'd be cleaner if we only show the footer when there is an update. Like why tell people you are checking for an update. Just do the work and tell me when I need to do something.

**Comment by ggalmazor** [comment]
OK, then:
- A toast that will pop up at the bottom edge of the window when there's an update available. Visible on all tabs.
- No toast or nothing when you're up to date
- The settings tab shows a permanent label with the Briefcase version you're running.
