### ISSUE TITLE
Provide more useful error when the URL is wrong

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#744]
https://forum.opendatakit.org/t/briefcase-unable-to-load-from-configured-source/20486 is the post that inspired this issue. I think maybe we should (in my order of preference)

1. If we see `Aggregate.html` we remove it and everything after on connect. This is my preferred approach even though it means you can't have a URL with Aggregate.html. Seems unlikely that someone would have that.

1. Provide a more useful error. Append `Did you enter the correct URL?` to the `Briefcase wasn't able to load forms using the configured source` message. 

1. Add a hint above the `Username cannot be a Google login` that says, `The URL must not include /Aggregate.html or anything after.` I hate this wording and taking up UI with a rare error.

**Comment by ggalmazor** [comment]
This is what I'm working on.

![aggregate dialog cleaning and validation](https://user-images.githubusercontent.com/205913/60729679-9997d300-9f43-11e9-9aef-7bb3600a3a0c.gif)

**Comment by yanokwa** [comment]
This looks pretty good to me. If the URL cleaning is safe, I'd probably leave not give users the notification. You have my green light.

**Comment by ggalmazor** [comment]
What about this then?

![image](https://user-images.githubusercontent.com/205913/60863504-38ad1b00-a221-11e9-9ccf-7e836c4b5c72.png)
