### ISSUE TITLE
Add language about where to get the project ID in the Central Server Configuration

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#748]
I think we can help people find their project ID when connecting to Central.

In the dialog, below the password, add this language.
`Project ID is the last number in the URL of the Project Overview`

For placement, look to the Aggregate Central Configuration dialog and match that placement.

**Comment by ggalmazor** [comment]
Whoever addressing this issue, remember that you have to set up your GUI Designer in IntelliJ to make changes to the source code (search for it on the Settings). Then you can make the change to the `CentralServerDialogForm.form` file, and rebuild the project to make the changes to the companion `CentralServerDialogForm.java` file.
