### ISSUE TITLE
Rename Maximum HTTP simultaneous connections

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#751]
`Maximum HTTP simultaneous connections` is too verbose. I think we should:
* Rename to `Maximum connections`
* Rename flag to `--mc` and `--max_connections`

If we did want to use all those words, the order has to be changed. It's subtle, but a native English speaker would say "Maximum simultaneous (or concurrent) HTTP connections". More at https://en.wikipedia.org/wiki/Adjective#Order.

Marking as priority because I think it should be fixed before a general release.

**Comment by ggalmazor** [comment]
- I think we should leave the "HTTP" part. 
- The "simultaneous" adjective has to do with how the HTTP client library works: it lets you define different limits to the total connections and the total simultaneous connections, but I agree that we can and should drop it.

**Comment by yanokwa** [comment]
Discussed with @lognaturel. She thinks the additional detail is fine, but the word order isn't. So, let's go with
* Rename to: `Maximum simultaneous HTTP connections`
* Keep the flag the same.
