### ISSUE TITLE
Adjust placement of max connections in UI

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#752]
This is what I see on macOS Mojave

<img width="411" alt="Screen Shot 2019-06-27 at 9 16 49 PM" src="https://user-images.githubusercontent.com/32369/60316869-5032fc80-9921-11e9-8446-321681cb0a9f.png">

I think we should place the M in Max connections in line with the left part of the Start pull checkbox.

**Comment by ggalmazor** [comment]
While working on #751 I've studied this just enough to see it could be virtually impossible to get this test aligned. Blame Swing.

**Comment by yanokwa** [comment]
@dcbriccetti As our resident Swing expert, do you think you could do this quickly?

**Comment by dcbriccetti** [comment]
Hi Yaw! I’ll have a look tonight, along with the other PR reviews.

**Comment by dcbriccetti** [comment]
@ggalmazor, it seems from your note that you think Yaw wanted to align the M in Max connections with the text following the checkbox graphic. That’s not the case.

Anyway, did you rule out replacing the checkbox’s border? 

<img width="1496" alt="Screen Shot 2019-07-10 at 1 11 18 AM" src="https://user-images.githubusercontent.com/55099/60952231-bcade400-a2af-11e9-838f-49fb07e11225.png">

```
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.io.PrintStream;

public class Main {
  private static PrintStream out = System.out;

  public static void main(String[] args) {
    var f = new JFrame("Experiment");
    var cp = f.getContentPane();
    cp.setLayout(new GridBagLayout());
    cp.setPreferredSize(new Dimension(200, 100));

    JLabel l = new JLabel("Maximum connections");
    Insets labelInsets = l.getInsets();
    System.out.println("Label insets: " + labelInsets);
    cp.add(l, createConstraints(1));

    cp.add(createCheckbox(labelInsets.left), createConstraints(2));

    f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    f.setLocationRelativeTo(null);
    f.pack();
    f.setVisible(true);
  }

  /** Creates a checkbox with a left inset (in an empty border) set to the requested value */
  private static JCheckBox createCheckbox(int leftInset) {
    JCheckBox cb = new JCheckBox("Start pull");
    Insets i = cb.getInsets();
    out.println("Checkbox insets before adjustment: " + i);
    cb.setBorder(new EmptyBorder(new Insets(i.top, leftInset, i.bottom, i.right)));
    out.println("Checkbox insets after  adjustment: " + cb.getInsets());
    return cb;
  }

  private static GridBagConstraints createConstraints(int gridY) {
    var gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = gridY;
    gbc.gridwidth = 1;
    gbc.anchor = GridBagConstraints.WEST;
    return gbc;
  }
}
```

**Comment by ggalmazor** [comment]
> it seems from your note that you think Yaw wanted to align the M in Max connections with the text following the checkbox graphic. That’s not the case.

Ugh, that makes sense! I was trying to align the label to the checkbox's label :/

Thanks!

**Comment by ggalmazor** [comment]
OK, I followed your advice, @dcbriccetti, and I got here (moved just the first checkbox):

| OS | Before | After |
| --- | --- | --- | 
| Linux | 
![image](https://user-images.githubusercontent.com/205913/60979712-769a6400-a333-11e9-9c74-982f7c58979a.png) | ![image](https://user-images.githubusercontent.com/205913/60979062-59b16100-a332-11e9-8f63-2adba6be65ad.png) |
| macOS | ![image](https://user-images.githubusercontent.com/205913/60979601-4a7ee300-a333-11e9-82f5-77757d80a0d6.png) | ![image](https://user-images.githubusercontent.com/205913/60979052-574f0700-a332-11e9-8dcf-67b6a0d4ebb9.png) |
| Windows | ![image](https://user-images.githubusercontent.com/205913/60979595-46eb5c00-a333-11e9-98b5-49603775384c.png) | ![image](https://user-images.githubusercontent.com/205913/60979040-5322e980-a332-11e9-8e50-171da2a1a9da.png) |

**Comment by dcbriccetti** [comment]
I agree with you, @ggalmazor. @yanokwa, I don’t have a clean solution, but would be happy to research more. This may answer your question, “do you think you could do this quickly?”.

**Comment by yanokwa** [comment]
Given that the two of you can't find a clean solution quickly, I think we've answered that we can't do this quickly. I'd vote to close this.

**Comment by ggalmazor** [comment]
Well, I forgot to mention the obvious solution of using the `MetalLookAndFeel` (the one we are using in Linux) for all platforms xD #endTheFragmentation
