### ISSUE TITLE
Forms to pull could possibly indicate the size of the content

### ISSUE THREAD

**Issue by rclakmal** [opendatakit/briefcase#76]
I'm not sure whether it is possible to fetch this information from the server. 
But could be a useful information for the user to get a rough estimation on how long will it take to download a particular form.

**Comment by yanokwa** [comment]
The API that is used is at https://github.com/opendatakit/opendatakit/wiki/Briefcase-Aggregate-API. I don't think you can get sizes, but you might be able to get the number of submissions, but I bet it won't be fast. @rclakmal if you want to explore this idea, I'd start there.

**Comment by rclakmal** [comment]
@yanokwa Thanks. Will look in to this.

**Comment by yanokwa** [comment]
@rclakmal I'm closing this because currently, it'd be very expensive on the server side to do this. See https://github.com/opendatakit/briefcase/issues/85#issuecomment-291324845 for more.
