### ISSUE TITLE
Push all forms when form_id is not specified

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#775]
**Problem description**
Similar to https://github.com/opendatakit/briefcase/issues/721, there isn't an easy way to push all forms from the storage directory into a server.

**Expected behavior**
Running a command like (and the Aggregate equivalent) will push all forms.

`java -jar briefcase.jar --push_central --storage_directory /home/ --odk_url test.central.com --project_id 1 --odk_email me@email.com --odk_password helloworld`

**Comment by yanokwa** [comment]
What do you think, @ggalmazor? Good idea? Doable to add into v1.17?

**Comment by ggalmazor** [comment]
Yes! This is even a `good-first-issue` because there's similar code in `PullFormFromAggregate`.

Maybe we can persuade @mayank8318 to take a shot at it :)

**Comment by acj** [comment]
Sure, I'll take a look this weekend.

**Comment by acj** [comment]
Yes, still working on this

**Comment by yanokwa** [comment]
@ggalmazor I think this should be re-opened because we haven't added support for Central (unless I'm missing something).

**Comment by ggalmazor** [comment]
I think you're right
