### ISSUE TITLE
Add error message when log in to non-existing project on Central on Pull and Push tab

### ISSUE THREAD

**Issue by kkrawczyk123** [opendatakit/briefcase#786]
#### Software versions 
Briefcase v1.16.x, Java v1.11.x, operating system, Aggregate v1.x.x, Collect v1.x.x...

#### Problem description
When input Id of non-existing Project on Central Connection Window and click on Connect button and log in but then “Briefcase wasn’t able to reload forms” I think that maybe some other error message should be displayed? The empty list is displayed and Pulling from so it suggests that you can Reload and pull from that project.  
On Push tab I am able to log in to the non-existing project, list of form is displayed and I am even able to Push a form there and I have “Success with errors” status which is totally misleading.

#### Steps to reproduce the problem
Try to log in to Central using Project Id that you are sure that does not exist on Central server. 

#### Expected behavior
I think that "Central not found" error could be enough or maybe more specific @ggalmazor what do you think?

**Comment by ggalmazor** [comment]
This is a great idea!

Central has [an API endpoint that could be used for this](https://odkcentral.docs.apiary.io/#reference/project-management/projects). Check the API docs at: https://odkcentral.docs.apiary.io

**Comment by mayank8318** [comment]
@opendatakit-bot claim
