### ISSUE TITLE
Smart Append Not working on CLI

### ISSUE THREAD

**Issue by chrissyhroberts** [opendatakit/briefcase#810]
#### Software versions 
Briefcase 1.17.0-beta.0, 
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

#### Problem description

I tried the CLI ```-sa```  / ```--smart_append``` flags with an export of an encrypted form
All submissions were exported and the smart append did not appear to work

#### Steps to reproduce the problem

```java -jar ODK-Briefcase-v1.17.0-beta.0.jar -pllc -E USER@domain.com -U https://SERVERURL -p PASSWORD -pid 1 -sd Data/ -id FORMID -e -smart_append -ed Output -f "FILENAME.csv" -pf ~PRIVATE.KEY.pem```

#### Expected behavior
All submissions export each time the command is run. No smart append

**Comment by ggalmazor** [comment]
Hi, @chrissyhroberts! I see you're pulling forms from Central. Currently, Central doesn't add a submission date to submissions like Aggregate does. Therefore, date range filters and `--smart_append` won't work as you expect.

I'm not sure how could we support these features for forms pulled from Central.
