### ISSUE TITLE
submission dates missing on export from Briefcase when pulled from Central

### ISSUE THREAD

**Issue by chrissyhroberts** [opendatakit/briefcase#811]
Software versions 

Briefcase v1.17.0-beta0, 
Java v1.x.x, operating system, Aggregate v1.x.x, Collect v1.x.x...
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

#### Problem description

SubmissionDate field is missing from exported data when data were pulled from a central server.

Affects encrypted forms. Not tested on unencrypted forms

#### Steps to reproduce the problem

Download a form from an aggregate survey using either GUI or CLI
Export the data (decrypting) and look at data. SubmissionDate field should be visible. 

Do the same thing but using a central surver, the SubmissionDate field is empty

**Comment by ggalmazor** [comment]
This is basically the same issue as #810 

The submission date information is added by Aggregate. Central doesn't change original submissions in any way, which means we don't have submission dates on submissions pulled from Central.
