### ISSUE TITLE
GUI fails to load after CLI used

### ISSUE THREAD

**Issue by chrissyhroberts** [opendatakit/briefcase#812]
### Software versions 
At least since Briefcase v1.16 
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
OS X 10.14.6

#### Problem description

Since at least 1.16, briefcase GUI fails to run if the CLI has previously been used. 

Error message

>The Java JAR file "ODK-Briefcase-v1.17.0-beta.0.jar" could not be launched" Check the Console for possible error messages.

Console output with keyword ```java``` reads as follows
 
```
default	14:56:54.887449 +0100	com.apple.WebKit.WebContent	Current memory footprint: 188 MB
default	14:56:55.844284 +0100	kernel	AGC:: [java pid 27676 mux-aware] exiting, non-mux-aware app count 4, runtime: 0:00:02.301
default	14:56:55.844439 +0100	kernel	AGC:: [java pid 27676 non-mux-aware] exiting, non-mux-aware app count 3, runtime: 0:00:02.302
default	14:56:55.844277 +0100	hidd	Connection removed: IOHIDEventSystemConnection uuid:80B90C1A-F4BC-4411-A909-B6196179FFE4 pid:27676 process:java type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:0
default	14:56:58.564398 +0100	com.apple.WebKit.WebContent	Current memory footprint: 281 MB
```

#### Steps to reproduce the problem

Pull and export with CLI and then try to start GUI. 

#### Other information 

Performing this command on CLI fixes the problem

```
java -jar ODK-Briefcase-v1.17.0-beta.0.jar -c
```

**Comment by ggalmazor** [comment]
Hi, @chrissyhroberts! Thanks for reporting this issue.

I can't reproduce the exact behavior you're describing. Could you describe with more detail the CLI ops you're running before trying to open the GUI? Also, could you describe the situation before running the CLI ops? Did you run the GUI before that? Did you have your sd set, etc?

In my computer, it looks as if the `-pllc` operation clears my prefs. When I run the GUI after pulling from the CLI, I'm asked again to set my sd location. I will investigate this in the mean time.

**Comment by ggalmazor** [comment]
OK. I've solved the issue I was having (losing prefs after CLI pull) and I will create a PR to fix it, but I'll wait for your feedback to add more fixes if I manage to reproduce what you're seeing.

**Comment by ggalmazor** [comment]
I've tried to reproduce the issue in a mac in case it was related with the operating system but I got the same results as in Ubuntu
