### ISSUE TITLE
"Update available" text doesn't wrap properly

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#815]
When I run master, this is what the "Update available" looks like. I think it should always be on one line and not wrap. Not sure if this is a macOS thing. My guess is that it's not easily fixable. Any ideas, @dcbriccetti ?

*On launch* -  😄
<img width="581" alt="Screen Shot 2019-09-17 at 12 39 08 PM" src="https://user-images.githubusercontent.com/32369/65073759-59dc6700-d948-11e9-8a71-e77a956a66af.png">

*Make window bigger* - 😟
<img width="678" alt="Screen Shot 2019-09-17 at 12 39 14 PM" src="https://user-images.githubusercontent.com/32369/65073761-59dc6700-d948-11e9-8572-7bfaa45aafd3.png">

*Make window smaller* -  😭
<img width="553" alt="Screen Shot 2019-09-17 at 12 39 21 PM" src="https://user-images.githubusercontent.com/32369/65073763-59dc6700-d948-11e9-9fcb-291bea009613.png">

**Comment by dcbriccetti** [comment]
Hi all. My guess is that it is easily fixable. Let me take a look now.

**Comment by dcbriccetti** [comment]
Something funky happens when the window is sized narrower than a certain width. Maybe @ggalmazor already knows about this. But to improve this specific situation, setting the label’s minimum size before adding it to the frame keeps it from wrapping. It is not perfectly centered when in that funky zone. I’m happy to look at the larger resizing issue, but I suspect @ggalmazor may already have plans for it.

```
versionLabel.setMinimumSize(versionLabel.getPreferredSize());
frame.add(versionLabel, versionLabelConstraints);
```

**Comment by ggalmazor** [comment]
Thanks, Dave!

>  I’m happy to look at the larger resizing issue, but I suspect @ggalmazor may already have plans for it.

Not really :D This is yet another chapter of Swing that I'd need to research. If you feel like you could save us some time, please, go ahead :)

I see that nothing really adapts to window size changes, right? I can see how there's a space to the right in one of Yaw's screenshots.

**Comment by dcbriccetti** [comment]
I’m looking at the broader resizing issue now.

**Comment by dcbriccetti** [comment]
I’m having success.

**Comment by ggalmazor** [comment]
It's looking great! Thanks, Dave!
