### ISSUE TITLE
-id flag does not appear to be optional on v1.17

### ISSUE THREAD

**Issue by chrissyhroberts** [opendatakit/briefcase#817]
#### Software versions 
Briefcase v1.17.0

#### Problem description
Using CLI tried omitting optional `-id` flag but briefcase reports that `-id` needs to be defined

#### Steps to reproduce the problem
java -jar ODK-Briefcase-v1.17.0.jar -sfl -sd "/DIR/" -U URL  -u admin -p password

#### Expected behavior
warning 'form id is required'

**Comment by chrissyhroberts** [comment]
Sorry, my mistake - hadn't added -plla

**Comment by ggalmazor** [comment]
Thanks for testing this anyway! :)
