### ISSUE TITLE
Reduce indirection and loose coupling with UI colors

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/briefcase#838]
#830 introduces new UI table sorting methods that are loosely coupled with the colors we're using to represent active/inactive buttons. The methods also introduce indirection between "something having X color" and "that something having Y business meaning".

We should extract all related business concepts into some artifact that can be reused in both placed. For example, a `ExportConfigurationButton` class, could have methods such as `isSelected(JButton button)`, or `sort(JButton o1, JButton o2)` among other. The goal would be to have all the business needs related to export conf buttons in a single place that can be used everywhere.

**Comment by jay4kelly** [comment]
@openda

**Comment by jay4kelly** [comment]
@opendatakit-bot claim

**Comment by ggalmazor** [comment]
Hi, @jay4kelly! Thanks for claiming this one. Since the solution will affect the design, we can discuss your ideas over in [Slack](https://slack.opendatakit.org/) if you want. I'll be around in the #briefcase-code channel.

**Comment by jay4kelly** [comment]
I've implemented the export configuration button. I'm now working on the detail configuration button.
