### ISSUE TITLE
export  with remove group names ignored with CLI

### ISSUE THREAD

**Issue by aurdipas** [opendatakit/briefcase#843]
#### Software versions 
Briefcase v1.17.1, Java v1.8.0_202, operating system Windows 10 Enterprise

#### Problem description
After pull. If I export via CLI with option --remove_group_names then the export has still group names. If I run the export via the UI all works corrrectly.
#### Steps to reproduce the problem
java -jar pathToBriefcase\ODK-Briefcase-v1.17.1.jar --remove_group_names  --split_select_multiples --smart_append --form_id myform --storage_directory ODK Briefcase StorageDir --export_directory myexportdirectory --export_filename myexport.csv

#### Expected behavior
The group names should be not in the export
#### Other information 
It works with Briefcase v1.17.0 and with the UI of Briefcase v1.17.1

**Comment by ggalmazor** [comment]
Closing issue, since the command should include `-e` in order to use the feature.
