### ISSUE TITLE
Use progress bars instead of text messages for local operations.

### ISSUE THREAD

**Issue by shivam-tripathi** [opendatakit/briefcase#85]
Presently during the process of extraction or pull etc. from server, messages like "Extracting ..." or "Downloading ..." is displayed. Instead of this if progress bars are shown, in my opinion, can enhance user experience. 
In case of pulls, https://github.com/opendatakit/briefcase/issues/76 may be relevant.

**Comment by mitchellsundt** [comment]
You can't display a progress bar without getting the total number of rows off of the server before you begin a pull (so you can calculate a percentage). And that would require a full table scan before beginning the pull, which would instantaneously double the costs you will incur on Google App Engine.

This is not a good thing. Closing.

**Comment by yanokwa** [comment]
I'm re-opening this issue because I think this would be a nice enhancement for the local operations where it's easy (e.g., exporting to CSV, pushing to Aggregate, pulling from SD card). @shivam-tripathi can you suggest an approach where we could do this for just local operations?

**Comment by shivam-tripathi** [comment]
@yanokwa I also believe it can be relevant for local operations. I'll look into this and get back to you.

**Comment by shivam-tripathi** [comment]
Since the extraction part is complete, we can now move to push part. ✌️

**Comment by yanokwa** [comment]
Closing because there is no nice place in the UI for these progress messages on the Pull/Push tabs.
