### ISSUE TITLE
On the initial launch if the user press "Cancel" on briefcase storage location selection dialog, user is end up having a disabled main window

### ISSUE THREAD

**Issue by rclakmal** [opendatakit/briefcase#87]
#### Software versions 
Briefcase v1.4.10, Java 1.8, OS Windows 7

#### Problem description
On the initial launch if the user press "Cancel" on briefcase storage location selection dialog, user is end up having a totally disabled main window. 

#### Steps to reproduce the problem
1. Just delete/move the briefcase storage directory and relaunch the app. You will get the storage location selection popup
2. Press "Cancel"
3. You are end up on a disabled main window with no option of going back. Only option is to close and relaunch. 

![b1](https://cloud.githubusercontent.com/assets/794011/24706026/8f8dbe0e-1a0e-11e7-965f-c017c28adb11.PNG)

![b2](https://cloud.githubusercontent.com/assets/794011/24706034/979fe540-1a0e-11e7-8488-966f242087f8.PNG)

#### Expected behavior
This would probably get fixed over the summer project for unified ui. A quick fix would be to remove the "Cancel" button. Because as of now, it doesn't serve any purpose

**Comment by yanokwa** [comment]
@rclakmal I'm not sure what to do here. Instead of removing the Cancel button, maybe we should quit the application? Or take the user to the Settings tab (and they can't leave that tab)?

Any other ideas @shivam-tripathi @icemc @nribeka?

**Comment by rclakmal** [comment]
@yanokwa Well technically, user shouldn't be able to cancel the selection of a folder since it's a mandatory requirement. 

I think your idea of directing to Settings tab is nice. But then, why wouldn't we just redirect the user to Settings page and make them do this setting on the first launch instead of this popup dialog ?

**Comment by yanokwa** [comment]
Redirecting to Settings seems like it'll be more complicated. You'd then have to prevent them from doing anything until they select a folder.

Another option is instead of Cancel, we replace that with Quit.

**Comment by rclakmal** [comment]
My point was not adding redirection. Rather, get rid of the popup and start the main window with the focus on Settings view and not letting user to browse other view until a folder path is set. 

However, Changing the button to a "Close/Quit" would be an easy option.

**Comment by rclakmal** [comment]
@yanokwa Shall I move forward with "Close" option and submit a PR?

**Comment by yanokwa** [comment]
So the options are:
1. Change dialog option to Close/Quit
2. Get rid of the popup, but lock the user to settings and add some language to settings screen to say that it's required.

I don't like the popup, but I bias towards Close/Quit as a solution because we'll probably be changing Briefcase's UX anyway and Close/Quit is a straightforward fix. Paging @lognaturel and @nribeka for feedback.

**Comment by rclakmal** [comment]
@yanokwa @nribeka @lognaturel I created a PR since it was a small change.  We can further discuss this through that PR.

**Comment by shivam-tripathi** [comment]
For a quick fix, in my opinion, we can remove the "Cancel" button with a "Quit" button. 
Settings tab can contain (in future) a lot of irrelevant requirements for a welcome page (presently it is empty), for example giving options related to form falsification or addition of other features (in future) which may require some form of user settings. So it would be a design decision to whether make a "Welcome page" which stores all ODK storage locations in the system, or go with a pop up or use the settings tab.

**Comment by rclakmal** [comment]
> Launching briefcase again doesn't necessary mean that I want to use the same location folder. Upon each launch, user can select the location.

Idea of multiple storage locations could be little make things complex from UI perspective and as far as I see it doesn't add big value  from user's perspective.

**Comment by yanokwa** [comment]
Thanks for all the ✨great✨ feedback.

I think we'll go with the Cancel/Quit option for now. I'll review the PR shortly. 👨🏿‍💻
