### ISSUE TITLE
Re-download deleted submission files during next pull from aggregate

### ISSUE THREAD

**Issue by icemc** [opendatakit/briefcase#92]
Software versions 
Briefcase v1.4.10,  operating system  windows 8,

 Problem description
When a form instance(submission file) obtained by pulling the form from aggregate is deleted from its folder(usually named as the instance id). During next pull Briefcase does verify that instance file is present before skipping it instead verify if the instance folder is present. By doing so deleted instances are not re-downloaded. This will probably happen to users who play around with the briefcase storage directory and form instances

Steps to reproduce the problem

- Pull a form say **New Widgets** from an aggregate server (in my case aggregate 1.0). After downloading the instances move to your briefcase storage location and locate where the instances of the particular form are stored(in my case ....\ODK Briefcase Storage\forms\New Widgets\instances). 

- enter into one or more instance directory and delete the submission file (submission.xml)

- Go to briefcase and re-pull the form instances. The deleted instances are not re-downloaded

 Expected behavior
The deleted instances should be re-downloaded during the next pull

Other information

**Comment by icemc** [comment]
@yanokwa i would like to work on this

**Comment by yanokwa** [comment]
@icemc Thank you for finding and documenting this bug. Please send in a PR!

**Comment by shivam-tripathi** [comment]
@yanokwa @icemc This is much more complicated. As I mentioned [here](https://github.com/opendatakit/briefcase/issues/77#issuecomment-289227508), if some one deletes/renames the media file, then upon exporting the file would be skipped, same thing as with submission xml file.
If we are considering tampering - you should in my opinion consider not just submission xml, but also media files. :) 
Also, @icemc you are just considering deletion - what if the file has been renamed? Maybe delete such a file.
All this is a big hassle. How to ensure data integrity when the entire storage is being compromised? I think this needs some discussion to prevent tampering - and give warning about the risks involved with the tampering if done intentionally.

**Comment by icemc** [comment]
@shivam-tripathi  regarding this [issue](#92) i think this solves the problem and i can confirm that the re-downloaded files are exported successfully.
Regarding the file tampering issue that u described above a new issue could be filled so that we could get a detail discussion regarding how to solve that.

**Comment by lognaturel** [comment]
I think there's only so much we can really do to save users from themselves. Dragging a submission out actually seems like it'd be an easy thing to do accidentally and I do think it makes sense to try to keep the local briefcase consistent on the next pull in case that does happen. Once a user starts renaming files, I kind of feel like they're on their own! But I can be convinced otherwise if someone wants to create an issue and make an argument for doing deeper integrity checks.

**Comment by lognaturel** [comment]
Oh, but if someone wants to do the same for media (just handling the delete case), I think that would be good as well.
