### ISSUE TITLE
Need for multiple workspaces (storage locations) in briefcase

### ISSUE THREAD

**Issue by rclakmal** [opendatakit/briefcase#93]
With regard to the discussion at #87,  there came the suggestion that may be briefcase could support multiple storage locations. This issue is to discuss, 

- Whether there are any practical use cases of multiple locations?
-  How should we handle this in UI? Should user be presented with an option to select "storage location" on each run? Can users switch workspaces during run time ?
- If it adds value to the user, what could be the technical challenges in implementing this

tagging @shivam-tripathi @yanokwa who were in the discussion from the beginning.

**Comment by yanokwa** [comment]
@mitchellsundt @wbrunette Can you please describe the need for multiple workspaces? I personally haven't used them and I don't know folks who have.

**Comment by yanokwa** [comment]
Closing because no one is demanding this and it would be a big change to the UI.
