### ISSUE TITLE
Fix style throughout the codebase

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/briefcase#94]
The code base is currently not very consistent when it comes to code style. We already have a good [checkstyle file](https://github.com/opendatakit/briefcase/blob/master/config/checkstyle/checkstyle.xml). It can be run with `gradle check` and eventually added to continuous integration. I also like to use the [checkstyle IDEA plugin](https://plugins.jetbrains.com/plugin/1065-checkstyle-idea) in IntelliJ.

To make sure this is done in an incremental and easy to test manner, contributors should **pick ONE check to uncomment**, update this issue so others know you've taken it, then review the errors, fix them committing changes for each file and then issue a pull request.

**Comment by shivam-tripathi** [comment]
Taking `<module name="CommentsIndentation"/>`

**Comment by shivam-tripathi** [comment]
Comment indentation.

**Comment by rclakmal** [comment]
Empty catch clauses

**Comment by rclakmal** [comment]
Single line java docs

**Comment by macalac** [comment]
Hey, just came across this project via up-for-grabs
Jumping on `WhitespaceAround`

**Comment by rockydcoder** [comment]
Indentation

**Comment by zstojanovic** [comment]
I'd like to help. OverloadMethodsDeclarationOrder.

**Comment by zstojanovic** [comment]
Also, I see that there is a number of Checkstyle rules which could be uncommented without issues - the code is already conforming to them.

@yanokwa - would it be desirable to uncomment all such rules? Should I prepare a PR with such change?

**Comment by lognaturel** [comment]
@zstojanovic Yes, that'd be a very nice PR to submit so we are sure those issues aren't introduced and we don't have to think about the checks again as others are enabled. Thanks!

**Comment by icemc** [comment]
Multiple variable declarations

**Comment by icemc** [comment]
Array type style

**Comment by icemc** [comment]
Missing switch default

**Comment by mayank8318** [comment]
Add an Intellij Settings file in the repository so that anyone can just import the settings and start coding :)
@yanokwa @ggalmazor

**Comment by ggalmazor** [comment]
> Add an Intellij Settings file

I think that could make an easier transition for first-time contributors :)

**Comment by yanokwa** [comment]
@ggalmazor I hesitate here because I'm not sure how we do this incrementally. That is, seems like it'd be ideal to have an IntelliJ settings file matches the checkstyle that CI evaluates the code against.
